videojs/http-streaming

- src/playback-watcher.js
- src/ranges.js
- src/segment-loader.js
- src/sync-controller.js
- src/util/logger.js
- src/videojs-http-streaming.js
- test/ranges.test.js
This adds a few more properties to the `hls.stats` object as well as uses the new `debug` logging level.
> feat: extend stats object

- src/dash-playlist-loader.js
- src/master-playlist-controller.js
- src/util/codecs.js
- src/videojs-http-streaming.js
- test/codecs.test.js
- test/configuration.test.js
- test/master-playlist-controller.test.js
- test/ranges.test.js
This PR contains 3 substantial changes
1. blacklists playlists that have codec information that is not supported by `MediaSource.isTypeSupported()` before initial playlist selection occurs.
2. small refactor of moving some codec helper functions from master-playlist-controller.js to util/codecs.js
3. `parseCodecs` can now parse `avc1` and `avc3`
> blacklist playlists not supported by browser media source before initial selection

- .babelrc
- package-lock.json
- package.json
- src/decrypter-worker.js
- src/master-playlist-controller.js
- src/media-segment-request.js
- src/mse/add-text-track-data.js
- src/mse/codec-utils.js
- src/playback-watcher.js
- src/ranges.js
- src/segment-loader.js
- src/vtt-segment-loader.js
- test/ranges.test.js
Start using node v8 for builds. Upgrade to the latest stable babel release and bring along browserify, babelify, and webworkify. Playback works on the test page and the tests all pass.
> Update babel, browserify, and other build steps

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
The source handler is currently resetting a player's eme options if they exist before source load, let's merge these options instead.
Merge existing `player.eme()` options
> fix: Don't reset eme options

- src/master-playlist-controller.js
- test/master-playlist-controller.test.js
This fixes an issue introduced by #34 that can happen with very short playlists with demuxed audio on very slow connections. If the connection is slow enough such that the audio segment loader can complete requesting the entire audio playlist and trigger `ended` before the main segment loader has completed its request for the first video segment, the changes in #34 will assume the stream is audio only and just rely on the audio segment loaders ended state, ignoring the main loader, because `startingMedia_` is set after the first request has been completed. This change will force waiting for both the main and audio loaders to trigger ended if the starting media of the main loader is still unknown.
> wait for both main and audio loaders for endOfStream if main starting media unknown

- package-lock.json
- package.json
- src/sync-controller.js
- test/sync-controller.test.js
The previous version of m3u8-parser had a bug that would associate the last `EXT-X-PROGRAM-DATE-TIME` tag with the start of the playlist.
This could cause problems in  live streams with the following properties
* ONE of:
1. `EXT-X-PLAYLIST-TYPE:EVENT`
2. a playlist with a sliding window, but viewed as the initial window is being filled, i.e. the playlist is still growing and segments are not yet being removed from the front
* Every segment has its own `EXT-X-PROGRAM-DATE-TIME` tag
When these conditions are met, each playlist refresh causes the `SyncController` to believe that there is a new sync point at the start of the playlist shifted by an amount that is equal to the amount of time added by new segments at the end. Since the playlist window is not actually sliding yet, the sync point …
> Fix program date time handling

- package-lock.json
- package.json
- src/master-playlist-controller.js
- src/mse/virtual-source-buffer.js
- test/loader-common.js
- test/media-segment-request.test.js
Regarding the `require.resolve`:
webpack resolves module names to ids during compile time. One of the issues with webworkify-webpack-dropin was that it used regex to search for the `require` statements to get the resolved module id so it could properly setup the bootstrapfn to start at the right module. This broke in some cases with minification because the regex would get messed up. By passing the module id directly from require.resolve, you dont have to do any of the regex work, and can just build the entire module list and have the starting id given to you. This problem is described in more detail here https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-293550845
> use webwackify for webworkers to support webpack bundle

- package-lock.json
- package.json
- src/dash-playlist-loader.js
- src/media-groups.js
- src/playlist-loader.js
- src/xhr.js
- test/dash-playlist-loader.test.js
- test/media-groups.test.js
- test/playback.test.js
- test/playlist-loader.test.js
- test/test-helpers.js
- utils/manifest/dash-live.mpd
This PR adds live support for DASH manifests. Since dash doesn't always need to update the playlists to get new segments (e.g. when template is in use, all future segments are known), playlists are "refreshed" by just re-parsing the manifest. The mpd-parser uses `Date.now` to calculate the current live window, which VHS can operate on like it does with HLS. Dash still has the concept of manifest refreshes that is separate from the live window, so the `masterPlaylistLoader` handles refreshing the xml, while the other loaders just ask the master loader for a freshly parsed xml whenever a "refresh" needs to happen.
NOTE: This will require the next version of mpd-parser that includes https://github.com/videojs/mpd-parser/pull/22
edit: merged https://github.com/mjneil/http-streaming/pull/1
> Live support for DASH

- package.json
Only publishes the required files for importing this module in a downstream project.
Closes #56
> ignore: Remove unecessary files from npm publish

- src/dash-playlist-loader.js
- src/playlist-loader.js
- src/playlist.js
- src/videojs-http-streaming.js
- src/xhr.js
Video.js exports an object and you can't do destructuring in imports, it's a special construct for named exports.
Also, modify the default export. Though, I can move that to a separate PR.
> fix: videojs doesn't export individual items but an object

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- index.html
- package-lock.json
- package.json
- test/karma.conf.js
This PR is to clean up the `overrideNative` option
> docs: update docs for overrideNative

- scripts/rollup.config.js
The minified build seems to be broken, this fixes the build by turning off the `typeof` transform.
> fix: minified build

- scripts/rollup.config.js
In videojs/video.js#5186, we noticed that the es builds weren't running babel, this can cause issues with uglify.
> fix: make sure that es build is babelified

- README.md
This adds some badges from http://issuestats.com/github/videojs/http-streaming to bring visibility to issue activity.
> ignore: issue-stats badges

- src/master-playlist-controller.js
- src/media-segment-request.js
- src/segment-loader.js
- src/util/608-captions.js
- src/util/text-tracks.js
- test/media-segment-request.test.js
- test/segment-loader.test.js
- test/text-tracks.test.js
Depends on https://github.com/videojs/mux.js/pull/197. 
This will parse captions from DASH fmp4 segments as each segment request is finished and add them to a corresponding text track(i.e CC1, CC2, CC3, CC4).
- requires an update to the mux.js dependency
> feat(captions): write in-band captions from DASH fmp4 segments to the textTrack API

- src/util/string.js
- src/vtt-segment-loader.js
- test/util/string.test.js
Fixes videojs/video.js#5070
Fixes the fallback text decoder. (https://stackoverflow.com/a/17192845)
> fix: convert non-latin characters in IE

- README.md
- docs/troubleshooting.md
https://github.com/videojs/http-streaming/issues/165
> Troubleshooting doc

- docs/troubleshooting.md
Update documentation to handle a Safari decode error scenario
> docs: add note for Safari captions error

- README.md
issuestats.com seems to be down. I opened https://github.com/hstove/issue_stats/issues/50. Removing the badges because issuestats seems to be relatively inactive. Will add the badges back if this is resolved.
> ignore: remove issue stats

- src/middleware-set-current-time.js
- src/videojs-http-streaming.js
- test/playback.test.js
Fixes #201 
Replay is broken because VHS is not loading the buffer when the video element seeks on replay. This previously worked because VHS would react to video element seek events. The seek caused by replay does not call `player.currentTime()` so the middleware does not kick in. This adds an additional middleware to call VHS's during play calls. 
Previously the play method of VHS would not go down the ended -> seek to 0 path because the tech would have already seeked to 0 on it's own, then emitted a play event.
> fix: fix replay functionality

- docs/troubleshooting.md
Update troubleshooting guide for Edge/mobile Chrome (see #211)
> docs: update troubleshooting guide for Edge/mobile Chrome

- src/master-playlist-controller.js
- test/master-playlist-controller.test.js
This tweaks the changes in https://github.com/videojs/http-streaming/pull/113 to fix a stutter in IE/Edge after the buffer is cleared. In the initial PR, seeking in place was sufficient to address this issue in Chrome, but we need to seek further behind/ahead of the current time in order to also fix the issue in IE/Edge.
> fix: stutter after fast quality change in IE/Edge

- README.md
- src/config.js
- src/playlist-selectors.js
- src/videojs-http-streaming.js
- test/configuration.test.js
- test/playlist-selectors.test.js
Some modern encoding techniques target the best quality at a given bitrate, to some extent irrespective of resolution. In such scenarios, users should be able to tell the player that the player size should be ignored during rendition selection in order to favor a pure bandwidth based decision which will maximize quality for the playback. 
- add a `limitRenditionByPlayerDimensions ` configuration option which can be set to false to ignore resolutions when doing rendition selection.
> add an option to ignore player size in selection logic

- src/videojs-http-streaming.js
- test/playback.test.js
Fixes #231, playback stalls if looping
On a seek to 0 when loop enabled, call `setCurrentTime(0)` on vhs.
> fix: ensure content loops

- README.md
- src/rendition-mixin.js
- src/videojs-http-streaming.js
- test/configuration.test.js
- test/rendition-mixin.test.js
#113 unfortunately _completely_ removed smooth quality switching for manual quality switches. This PR adds it back via a configuration option.
- Add `smoothQualityChange` config option
- Merge it with a possible source option of the same name
- Select `fastQualityChange` or `smoothQualityChange` using a ternary that checks the aforementioned config option
> add back manual smooth quality changes via smoothQualityChange flag

- src/videojs-http-streaming.js
Uses a new videojs-contrib-eme API to set up EME immediately and not wait for `encrypted`
https://github.com/videojs/videojs-contrib-eme/pull/61
> fix: immediately setup EME if available

- package-lock.json
- package.json
Includes the changes for [5.0.0 and 5.0.1](https://github.com/videojs/mux.js/compare/v4.5.1...v5.0.1)
> chore: update mux.js to 5.0.1

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
HLS already throttles reloads of the final playlist, however, DASH does not. This adds the throttling behavior to the DASH playlist loader.
To see the behavior:
1) Go to https://videojs.github.io/http-streaming/
2) Enter the source as: https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd and the mime type as: application/dash+xml
3) Click play
4) Open the console and go to the network tab
5) Click "Offline"
The failed requests will shoot up as fast as can be processed (since the retries are immediate).
The fix makes it so that retries are only made at half the target duration.
> Throttle final playlist reloads when using DASH

- src/segment-loader.js
- test/segment-loader.test.js
The segment metadata is currently missing the information that comes from the `EXT-X-PROGRAM-DATE-TIME`. 
I've added the `dateTimeObject` & `dateTimeString` to the segment data object. The information as already coming through from the buffer, only missing to be added to the segment data object that's _published_.
> Adding missing manifest information on to segments (EXT-X-PROGRAM-DATE-TIME)

- README.md
> Add README entry on DRM and videojs-contrib-eme

- .travis.yml
- test/karma.conf.js
- test/master-playlist-controller.test.js
- test/videojs-http-streaming.test.js
> chore: add clock.ticks to now async operations in tests

- README.md
- src/playlist-loader.js
- src/videojs-http-streaming.js
- test/playlist-loader.test.js
Exposes the m3u8-parser's custom parser API on the source object
> feat: expose custom M3U8 parser API

- src/mse/virtual-source-buffer.js
- test/mse/html.test.js
This is a proposed fix for https://github.com/videojs/http-streaming/issues/130. Instead of adding text-track data only to video segments, we are now adding to all segments.
One change bringing the addTextTrackData invocation outside of the conditional which checks for video buffer.
Sources:
With audio only
http://li720-23.members.linode.com/hls/audio.m3u8
With video and audio
http://li720-23.members.linode.com/hls/video.m3u8
> fix(id3): cuechange event not being triggered on audio-only HLS streams

- README.md
- package-lock.json
- package.json
- src/playlist-loader.js
- src/videojs-http-streaming.js
- test/configuration.test.js
- test/playlist-loader.test.js
Exposes parser and mapping APIs from the m3u8-parser module.
> feat: expose custom M3U8 mapper API

- src/playlist-loader.js
Porting the pull request to new http-streaming after the old repo was archieved:
https://github.com/videojs/videojs-contrib-hls/pull/1425/
It's a one-line-fix.
See https://github.com/videojs/http-streaming/issues/345
Possibly related issues:
https://github.com/videojs/videojs-contrib-hls/issues/442
https://github.com/videojs/videojs-contrib-hls/issues/550
https://github.com/videojs/videojs-contrib-hls/issues/555
https://github.com/videojs/videojs-contrib-hls/issues/111
This updates the logic for deciding whether a playlist has changed to check the endList property as well.
> [Bugfix] m3u8 playlist is not updating when only endList changes

- src/master-playlist-controller.js
> fix: Prevent exceptions from being thrown by the MediaSource

- src/playlist-loader.js
- test/playlist-loader.test.js
See videojs/videojs-contrib-hls#1424
Possibly related issues:
videojs/videojs-contrib-hls#442
videojs/videojs-contrib-hls#550
videojs/videojs-contrib-hls#555
videojs/videojs-contrib-hls#111
This updates the logic for deciding whether a playlist has changed to check the `endList` property as well.
> Add fix for playlist not updating when only endList changes

- src/middleware-set-current-time.js
This bug is somewhat hard to reproduce as it only happens when another middleware reports a `currentTime` that is not the same as what vhs suggests.
> fix: Fix video playback freezes caused by not using tech current time

- src/videojs-http-streaming.js
Right now Edge will sometimes buffer indefinitely once a video that is set to loop moves back to `currentTime` 0. 
After investigating this it appears that Edge does not set `tech.seeking()` to `true` during a `seeking` event for looping back to `currentTime` 0. Normal `seeking` events do set `tech.seeking()` to true, as expected. 
I don't think that we need the extra check for `seeking` on the `tech` at the start of the if statement. If we just had a `seeking` event it should be fairly evident that we are seeking. I also think that the other two checks (for currentTime, and loop) should be enough to have this only happen when a video is looping.
> fix: Prevent infinite buffering at the start of looped video on edge

- src/master-playlist-controller.js
A lot of the time we call `seekablechange` and log `seekable` changes when seekable is the same as it previously was.
> fix: only fire seekablechange on a change

- src/segment-loader.js
- test/segment-loader.test.js
Exposes the missing `custom` segment property in the segment metadata track, this property is present on the segment object parsed by VHS.
> fix: expose `custom` segment property in the segment metadata track

- src/mse/add-text-track-data.js
When we get an unsupported id3 frame, we don't parse its time. This ends
up coming back to us as NaN in the timing for the frame. Instead of
trying to create a cue for this frame, ignore it whenever the time isn't
a number or when it isn't finite.
Fixes videojs/video.js#5823
> fix(id3): ignore unsupported id3 frames

- README.md
I know it's minor, figured I'd send it over while I'm learning / reading over the docs...
> Fixes deadlink in README.md to docs/intro.md

- README.md
- package-lock.json
- src/bin-utils.js
- src/master-playlist-controller.js
- src/media-segment-request.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/configuration.test.js
- test/master-playlist-controller.test.js
- test/media-segment-request.test.js
- test/segment-loader.test.js
- test/test-helpers.js
- test/videojs-http-streaming.test.js
Adds an option to force the player to cache encryption keys instead of requesting for every segment. Defaults to `false` for backwards compatibility.
Addressess #140 
todo/future enhancement: Use HTTP Expires header to expire our internal cache per https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.2.3
> feat: add option to cache encrpytion keys in the player

- src/mse/virtual-source-buffer.js
- src/source-updater.js
- test/source-updater.test.js
Per the MSE spec, [calling `abort()` during a `remove()` will throw an `InvalidStateError`](https://www.w3.org/TR/media-source/#dom-sourcebuffer-abort). During `dispose()` of the `SourceUpdater`, we call `this.sourceBuffer_.abort()` without waiting for the pending operation to finish, even if that operation is a `remove`. Thus, we can get an `InvalidStateError` on `dispose`.
Track whether we're in the process of removal. If `dispose` happens before we finish the `remove`, add the dispose function as a handler for `updateend`.
> Fix: On dispose, don't call abort on SourceBuffer until after remove() has finished

- src/source-updater.js
- test/source-updater.test.js
Long story short, I hit a condition where non-muxed HLS wouldn't start playing sometimes. This is because it's possible to end up in a condition where one `SourceUpdater` gets both a `timestampOffset` and an `appendBuffer` call before the other `SourceBuffer` is added to the `MediaSource`. Since [`timestampOffset` queues a callback](https://github.com/videojs/http-streaming/blob/faf1198b9cbaddc89857cf19895d3c185708cc96/src/source-updater.js#L178-L180), but does not trigger an `updateend` on the `SourceBuffer`, the already-queued `appendBuffer` call is never processed, and thus a `SegmentLoader` ends up waiting forever.
For easy reproduction of the problem, you can simply delay the creation of the audio `SourceBuffer`, like so:
```diff
diff --git i/src/source-updater.js …
```
> fix: run callbacks after setting timestampOffset

- scripts/rollup.config.js
I was annoyed with `npm run watch` not working properly, so I decided to try to fix it. I don't know if this is the right approach, but I did what video.js is doing with adding modules into the `external` config key.
With this + videojs/video.js#5966, you can change a file in VHS and it will be compiled into video.js. It takes a bit to compile, but I found that I would sometimes get some weird behaviour if I was loading both `video.js` and `videojs-http-streaming.js`.
Added the modules that caused compilation failure to the `external` config key for CommonJS and ES output.
> fix: change rollup config so that npm run watch works

- src/media-segment-request.js
IE11 doesn't support slice on TypedArrays, instead, do it manually if
the TypedArray doesn't have slice.
> fix(HLSe): slice keys properly on IE11

- src/media-groups.js
- src/sync-controller.js
- test/media-groups.test.js
- test/sync-controller.test.js
This pull requests fixes some HLS livestream timeouts that were happing before playback would even begin. I will go over them in code comments.
> Fix: livestream timeout issues

- README.md
- src/master-playlist-controller.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
Adds a top level option for handlePartialData
We should merge this after #519 So that we can update the test page to have tis option.
> feat: Add handlePartialData as a top level option

- src/master-playlist-controller.js
- src/segment-loader.js
- src/source-updater.js
- test/playback.test.js
- test/segment-loader.test.js
- test/source-updater.test.js
- test/videojs-http-streaming.test.js
Currently the way `endOfStream` works in the tba branch:
1. Does not make much sense as most `sourceBuffer` and `mediaSource` operations go through the `sourceUpdater` now
2. `endOfStream` isn't called correctly whenever a rendition switch or audio switch happens at the end of a stream.
This full request fixes that.
> fix: do not always set ended_ to false on sourceopen

- index.html
- scripts/index.js
* Adds back in url type specifier
* Fixes issues and styling in firefox
* fixes dispatch event in ie 11
> fix: issues with the demo in ie11 and firefox

- index.html
- package-lock.json
- scripts/index.js
- scripts/netlify.js
- src/segment-loader.js
With the current implementation a separate video and audio segment loader will try to use the combined buffered value, this causes all kinds of issues. For high bit rate sources we see a lot of append over max on source buffer errors.
> fix: Return the correct buffer for each segmentloader

- src/source-updater.js
- test/source-updater.test.js
When audio is appended before video the media source timestamp may be off which causes playback to stall after it starts. It can also make it seem like the video is frozen for the first few seconds of playback. This is the fix.
> fix: delay first audio appends when we have not done a video append

- src/segment-loader.js
- src/vtt-segment-loader.js
- test/segment-loader.test.js
608 captions can currently "multiply", ie The same cue and text for a different rendition is added and both the caption from the old rendition and the new rendition are shown at the same time. This happens because:
1. We switch renditions segments are downloaded and parsed for captions.
2. We add the cues for those captions to our tracks.
3. If we already had similar cues from the previous rendition, we don't do anything about it. This causes duplicated captions!
The Fix:
Before adding caption cues to a track, we remove any existing caption cues at those times.
> fix: Prevent double 608 captions on rendition change

- src/segment-loader.js
This contains the change originally from #565 but broken out so that we can talk about it.
Increasing playbackRate showed a race condition where an alt audio track wouldn't have, tracks or timescales set correctly after the first request
> fix: track does not exist race condition

- test/source-updater.test.js
Sometimes this test fails on Firefox, because audio is appended to the audio buffer, before video, even though we call appendBuffer on video first. This causes the test to end without running the video appendBuffer callback and we get one less assertion than we expect.
> test: Fix a tests that could fail via a race condition

- src/master-playlist-controller.js
- src/media-segment-request.js
- src/util/codecs.js
- test/master-playlist-controller.test.js
- test/util/codecs.test.js
fix: prioritize playlist codecs over mux.js codecs, so encrypted content doesn't fail
> fix: prioritize playlist codecs over mux.js codecs, so encrypted content doesn't fail

- scripts/rollup.config.js
- test/custom-assertions.js
- test/master-playlist-controller.test.js
- test/source-updater.test.js
- test/util/buffer.test.js
As the commit message says, we currently modify the assertion prototype. Initially this caused a lot of confusion for me because QUnit has nothing in the docs about the assertions we were using. I think adding to the prototype of a library is a bad practice.
> test: Make custom assertion functions instead of adding to QUnit

- package.json
When testing the netlify script @gkatsev found that we try to lint the deploy dir, which we should not do.
> chore: do not lint deploy dir

- src/media-segment-request.js
- src/segment-loader.js
- src/source-updater.js
In the segment loader, we checked for `this.loaderType` but should be checking against `this.loaderType_`.
In addition, this passes the segmentInfo to the appendBuffer action, so we can have a more meaningful debug log.
Also, don't log audio buffer or video buffer data if they don't exist.
> fix: check loader type properly

- .travis.yml
Bad bash, variables start with `$` and we probably should wrap in quotes for good measure... woops...
> chore: fix tests on travis

- src/segment-loader.js
- src/sync-controller.js
- test/segment-loader.test.js
Currently, the value for `timestampOffset` comes from `segment.end`, which is set from the DTS values returned by the tsprobe. This is not the correct value to use for the `timestampOffset`, and can result in missing frames or gaps between segments.
The TBA/LHLS branch (now #master) improves upon the current calculation of the `timestampOffset` by using the buffered end value instead of `segment.end`. However, this can still result in gaps in some cases if there is a difference between the pts time and dts time of the first frame that exceeds an internal browser threshold (in Chrome this threshold seems to be right around .08). The way to address that is to factor in the difference between the pts start time and dts start time of the first frame: `timestampOffset = buffered.end - (ptsTime …
> fix: improve timestampOffset calculation to avoid gaps

- test/source-updater.test.js
- test/videojs-http-streaming.test.js
localStorage tests often fail on ie11/edge presumably due to storage space issues on browserstacks end. 
`setDuration waits for audio buffer to finish updating` often fail as well because edge sometimes throws an error on `appendBuffer` or `setDuration`
> test: skip more tests on ie11 and edge for now

- src/segment-loader.js
- src/transmuxer-worker.js
- src/videojs-http-streaming.js
gzipped size goes from 
`89525` -> `74033`,  `15492 bytes gzipped` or a ~17.5% decrease 
~~Due to dropping the main export of ` Decrypter,	AsyncStream,	 decrypt` this will probably have to be a major version, but I think it is warranted~~ EDIT: this part was removed, and an issue has been filed #627
> perf: better mux.js imports, save 15492 bytes gzipped, ~17.5% decrease in size

- scripts/rollup.config.js
`89525` -> to `88623` no noticeable increase in minify time.
passes are not an unsafe transformation either.
> perf: Switch to two passes in terser save 903 gz bytes

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
Currently, VHS augments the EME key systems of DASH sources with DRM-related information from the manifest. In order to support Widevine HLS content, we will need to expand this key system handling to work for HLS content as well. Since the existing logic is based on the assumption that we are dealing with DASH, and thus unmuxed video and audio, some tweaks are needed in order to account for the fact that HLS can be either muxed or unmuxed.
- get video and audio mimeTypes and codecs from `mainSegmentLoader.mimeType_` and `audioSegmentLoader.mimeType_` instead of playlist attributes, since we already do some of the [work needed](https://github.com/videojs/http-streaming/blob/1.x/src/master-playlist-controller.js#L1094) to format those strings for EME when we initially setup the source …
> feat: setup EME key systems for HLS as well as DASH 

- package-lock.json
- package.json
- src/sync-controller.js
- test/segment-loader.test.js
- test/sync-controller.test.js
Starting in v69, Chrome started rolling out [changes](https://developers.google.com/web/updates/2018/08/chrome-69-media-updates#pts) to report media buffer ranges and durations based on `pts` (presentation timestamp) values instead of `dts` (decode timestamp). Until recently, this project was still expecting the former behavior, setting `timestampOffset` values using dts values. This occasionally conflicted with the new Chrome behavior, resulting in gaps in the buffer that negatively impacted playback. We addressed this issue in #616 for .ts segments, but apparently not fmp4s. This PR achieves the same thing as #616 for fmp4 segments by modifying the `probeMp4Segment_()` function to use "composition time" values instead of decode time. (**Note:** fmp4 timing does not rely on the same …
> fix: improve timestampOffset calculation for fmp4s

- src/dash-playlist-loader.js
- src/playlist-loader.js
- src/rendition-mixin.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/dash-playlist-loader.test.js
- test/playback.test.js
- test/playlist-loader.test.js
- test/rendition-mixin.test.js
- test/test-helpers.js
- test/videojs-http-streaming.test.js
Fixes #663 
WIP. I still need to fix and add unit tests.
Instead of using playlist `URI` as a unique identifier for streams, create an `id` property that is the combination of `uri` and index within the master manifest.
> support multiple stream-inf with same URI

- src/videojs-http-streaming.js
PlayReady media key setup (done via `msSetMediaKeys()` in IE11) is a side effect of the on-demand `player.eme.initializeMediaKeys()` call and fails because the video `readyState` is still 0 at that point. For `msSetMediaKeys()` to work the `readyState` apparently has to be > 0. Therefore, we need to bypass `initializeMediaKeys()` in IE11 and delay the `msSetMediaKeys()` call until the video element is ready.
Add a `!(videojs.browser.IE_VERSION === 11)` condition before calling `initializeMediaKeys()`, so that we fall back to the old [contrib-eme key setup behavior](https://github.com/videojs/videojs-contrib-eme/blob/master/src/plugin.js#L255) that waits until the `msneedkey` event in IE 11, and continue to use the on-demand key setup behavior everywhere else.
> Don't try to initialize media keys in IE11

- src/dash-playlist-loader.js
- src/playlist-loader.js
#670 fixed #663 but I realized that it would be considered a breaking change as you could no longer use uri to reference playlists. While this will still not work properly for stream-inf with the same URI, the majority of sources that do not do that should still be able to work using uri.
> add uri playlist references for backwards compatibility

- src/dash-playlist-loader.js
- src/playlist-loader.js
- src/rendition-mixin.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/dash-playlist-loader.test.js
- test/playlist-loader.test.js
- test/rendition-mixin.test.js
- test/test-helpers.js
- test/videojs-http-streaming.test.js
Fixes #663 
backport of #670 
Instead of using playlist `URI` as a unique identifier for streams, create an `id` property that is the combination of `uri` and index within the master manifest.
> 1.x: support multiple stream-inf with same URI

- src/videojs-http-streaming.js
Pulling the change from #682 into the master/tba-lhls work
> fix: don't try to initialize media keys in ie11, #682 master

- src/master-playlist-controller.js
- src/segment-loader.js
- test/loader-common.js
When joining a live stream, VHS starts playback at a time of 0,
regardless of how long the stream has been playing. This means that the
playlist will start with sync info of time 0 for the first media index.
However, if the stream "played" (either via API, autoplay, etc.) before
a playlist was downloaded, then after the playlist downloaded the
loader would reset the sync info, erasing the assumed time 0 for first
media index, and the player would request segments ad infinitum, never
able to place them in the timeline and get a new sync point.
This separates the notion of played between play initiation and playback
of content (progress on the timeline), in order to ensure that the
initial sync info is maintained.
This continues the work done by @gkatsev in …
> Fix live startup failures when play happens before playlist is downloaded

- index.html
- scripts/netlify.js
- src/rendition-mixin.js
- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
- utils/stats/index.html
Quality levels is not being populated due to a race condition where the tech is not ready until after we have fired `selectedintialmedia`. You can get this to happen by in chrome by loading the tab in the background for 10s or by using a slow browser like ie 11, where it will happen in the main tab.
1. Open `index.html`
2. Open the link to `Stats` in a new page, and wait 10s before switching to that tab.
3. Note that the `qualityLevels` do not show up on the page, and `player.qualityLevels().levels_` is a 0 length array
4. Note that `player.representations()` has the correct representations in the returned array. 
5. Note that the `qualityLevels` buttons do not show up on the page.
1. The first commit deploys the stats page, and fixes a bug with the stats page. That allows this bug to be …
> fix: race condition preventing qualityLevels from being populating

- package-lock.json
- package.json
- src/media-segment-request.js
- src/segment-loader.js
- src/segment-transmuxer.js
- src/transmuxer-worker.js
- src/util/segment.js
- test/segment-loader.test.js
~~**I am not sure if this is correct or not, and will need feedback. This does fix the issue from #616 though**~~
#616 and #660 but for master. Since we already set `timestampOffset` to `bufferedEnd` in master all that was needed here was to change the `start` times that we probe for so that they use `ptsTime`. When trying to minus dtsTime and ptsTime as seen in #616 playback never works. After setting it to just use the `ptsTime` value everything works.  From my testing `ptsTime` works **a lot more consistently** then `dtsTime` 
Depends on https://github.com/videojs/mux.js/pull/300
> fix: Use pts value for timingInfo probes (#616/#660 from 1.x)

- package-lock.json
- package.json
- src/media-segment-request.js
- src/segment-loader.js
- test/loader-common.js
- test/master-playlist-controller.test.js
- test/media-segment-request.test.js
- test/playlist-loader.test.js
- test/test-helpers.js
- test/videojs-http-streaming.test.js
- test/vtt-segment-loader.test.js
* Add check to media-segment-request for empty responseText when handling partial data
This was not needed in the past, as the responseText property of a sinon response was
anually set by VHS' test helpers. However, sinon now clears out the responseText property
on a response, the mime type override trick doesn't work like it would in a browser. The
additional check to the code should prove harmless, and acts as a guard against browsers
which don't implement the mime type override trick in the same way.
* Add an abortFn callback to media-segment-request to fix abort tracking in
mediaRequestsAborted
In the previously used version of sinon (v1.10.3), aborts of requests triggered the XHR
callback. In the XHR standard however, this does not happen. Later versions of sinon fixed
this issue. …
> Update sinon to v8.1.1 and fix abort tracking in mediaRequestsAborted

- src/dash-playlist-loader.js
- src/master-playlist-controller.js
- src/playlist-loader.js
- src/segment-loader.js
- src/source-updater.js
- src/sync-controller.js
A lot of the classes and major objects extend EventTarget, which has no notion of disposing listeners. We need to trigger dispose on our own and call `off` to remove all listeners on `dispose`. I noticed that we aren't even disposing most objects.
> fix: add dispose functions and fix memory leaks

- README.md
Updates the `overrideNative` section, since that's a frequent cause of confusion, or not using it is a frequent cause of issue with bad native HLS implementations.
Removes using it a source option, because that doesn't work.
> docs: Update overrideNative information

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
This particular issue was noticed when rendition switches while playing
live DASH resulted in the audio buffer no longer filling, and the content
stopping playback after finishing the currently buffered media.
In the code, the media groups module paused the audio playlist loader, which
cleared its refresh timeout, but on calling load to resume the loader, the
refresh timeout was not set, as it is in the normal playlist loader. The
added logic matches the normal playlist loader's load function.
Copy of https://github.com/videojs/http-streaming/pull/736 for master
> fix: resume live DASH playlist refreshes after pausing and loading DASH playlist loader

- src/segment-loader.js
- test/segment-loader.test.js
- test/videojs-http-streaming.test.js
Previously, if the seekable window for the content started at 0
(generally denoting a VOD or LIVE DVR playlist), the back buffer would
not be trimmed. With high bitrate and/or longer content, this could
lead to an APPEND_BUFFER_ERR due to the buffer exceeding the max
allowed buffered bytes.
In order to help alleviate this issue, particularly with the increase in
high bitrate content, the back buffer is now trimmed to a reasonable
length, even if the seekable window starts at 0.
> fix: trim 30s back from playhead even for VOD and LIVE DVR content

- src/segment-loader.js
Currently master waits for zero length segments to append, and they never will. So playback stalls and the video is assumed to have ended once we reach a zero length segment. Once I fixed that I realized that we have to set timingInfo start to zero for a zero length segment as we won't get a `timinginfo` event from mux.js.
> fix: update timestamp and dont wait for append, for zero length segments

- src/segment-loader.js
- test/segment-loader.test.js
See https://github.com/videojs/http-streaming/pull/502
Added some modifications to make testing easier and better organize the code, but let me know if you disagree with those changes.
> fix: only reset syncController if we passed a discontinuity

- index.html
before:
after:
Also, it reduces the width of the label to the grey area so that the entire line isn't the target and you don't accidentally reload the player when clicking randomly on the page.
> chore: improvements to demo page options

- src/segment-loader.js
- src/vtt-segment-loader.js
- test/master-playlist-controller.test.js
- test/vtt-segment-loader.test.js
In DASH it's very common to provide the captions as one file rather than
having it be segmented VTT. It's possible to do the same in HLS, though,
it isn't common.
When we switch between tracks, we remove all the cues for the
duration of the video because the cues are no longer needed. Also, as we
re-download segments, the associated cues should be re-added.
Unfortunately, this the case of a single "segment", we don't get more
segments and the cues don't get re-added. Therefore, for non-live when
we have one segment, we shouldn't remove the cues.
This fixes the case both for turning the track on and off but also for
seeking.
> fix(segment-loader): resetEverything should remove through Infinity

- src/master-playlist-controller.js
- src/vtt-segment-loader.js
- test/vtt-segment-loader.test.js
This is a fixed up and rebased version of #719.
It technically requires a Video.js change as well (https://github.com/videojs/video.js/pull/6410) for the full feature to function but each PR can be merged separately.
Once this is  approved, I'll merge this manually to maintain authorship.
> fix: add native cues when using native text tracks

- .gitignore
- src/master-playlist-controller.js
- test/master-playlist-controller.test.js
This is #779 but against master.
> fix: null check return value of selectPlaylist

- src/segment-loader.js
- test/segment-loader.test.js
When switching to alternative audio and turning off audio on the main segment loader we are not removing the original audio data from the main segment loader. This means that we start adding new audio onto the old audio causing all kinds of issues.
> fix: Remove current sourceBuffer audio on disable

- src/playlist-selectors.js
Currently player dimensions is not determined correctly and cause lower quality playlist to be played.
This fix calculate real player dimensions on devices that have devicePixelRatio greater than 1 (retina displays and most mobile devices).
multiply player width and height by devicePixelRatio .
> Take devicePixelRatio into account

- src/master-playlist-controller.js
- src/playback-watcher.js
- src/videojs-http-streaming.js
- test/playback-watcher.test.js
This reverts commit 6c68761b5d06d951d7ed20cbd5bb63f324ad2c47.
This helps address #378 and  videojs/video.js#6444.
> Revert "fix: Use middleware and a wrapped function for seeking instead of relying on unreliable 'seeking' events (#161)"

- src/playlist-selectors.js
> fix: take devicePixelRatio into account during ABR 

- README.md
- src/playlist-selectors.js
- src/videojs-http-streaming.js
- test/configuration.test.js
Due to the Covid-19 pandemic, we are turning this into an option instead of enabling it by default to limit the amount of bandwidth used. We may make this be set to true by default in a future update.
> fix: put devicePixelRatio behind useDevicePixelRatio option

- src/master-playlist-controller.js
- src/segment-loader.js
- src/timeline-change-controller.js
- test/loader-common.js
- test/master-playlist-controller.test.js
- test/segment-loader.test.js
- test/timeline-change-controller.test.js
In order to properly sync audio and video for demuxed content when there are discontinuities, one of the streams must follow the timing of the other. For VHS, video was chosen (historically) to be the source of truth for media timing, and audio was manipulated to fit the media timing.
In order to properly fit audio to the video timeline, audio must know the timing information of video before it is appended, and video must wait for audio to cross a discontinuity before it crosses, so as not to set the timestamp offset or other associated timing information for audio before audio is done with appends along its current timeline.
As such, a TimelineChangeController object was added, in order to facilitate discontinuity crossings where audio and video streams each wait until the other is ready …
> fix: audio and video syncing for demuxed content with discontinuities

- test/master-playlist-controller.test.js
- test/videojs-http-streaming.test.js
Since my `devicePixelRatio` is `2` by default tests are failing for me right now. This pull request fixes that by setting `window.devicePixelRatio` to `1` during testing and resets it to the native value afterward.
> test: Set devicePixelRatio to 1

- test/master-playlist-controller.test.js
- test/videojs-http-streaming.test.js
Noticed that we were leaking web workers in a few places and cleaned it up.
> test: dispose objects to prevent web worker leaks

- package-lock.json
- package.json
- src/master-playlist-controller.js
- src/media-segment-request.js
- src/playlist-selectors.js
- src/segment-loader.js
- src/source-updater.js
- src/util/codecs.js
- src/videojs-http-streaming.js
- test/master-playlist-controller.test.js
- test/videojs-http-streaming.test.js
Depends on https://github.com/videojs/vhs-utils/pull/10
Ultimately this pull request solves issues multiple issues:
1. We can now answer what codecs the muxer supports
2. We can rely on muxer support for ts segments
3. We can rely on browser support for fmp4 segments
4. We can rely on muxer and browser support separetly
> fix: better codec handling

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
- test/master-playlist-controller.test.js
Previously, some media references in the DASH playlist loader weren't properly updated,
meaning that they were references from the old master. This broke blacklisting, where the
old playlist was blacklisted, but the playlist selector, using the newer playlist
references, could select the same playlist (but a new reference).
> fix: update media references in DASH playlist loader to ensure they are from master

- index.html
- scripts/index-demo-page.js
- scripts/netlify.js
- scripts/sources.json
Move sources into a JSON file that we can use to populate the list. Eventually, we could have the features for each item be in the JSON file and then have a better UI on the demo page that would allow filtering by those features. Though, currently, the features are only used for the live and low-latency streams to move them into the live and low latency opt groups.
> chore(demo): new sources, generate selection list from a JSON file

- src/segment-loader.js
- src/vtt-segment-loader.js
- test/segment-loader.test.js
- test/vtt-segment-loader.test.js
The VTT loader maintains its own time mappings. Saving the timing info
on the segments and in the sync controller can negatively impact stream
sync, especially for VTT.
Prior to transmux before append, this timing info wasn't saved. It was
inadvertently added as the segment loader methods were refactored.
> fix: don't save segment timing info in sync controller for VTT segments

- src/videojs-http-streaming.js
Remove assumption that this library is starting up inside of a DOM environment. Many circumstances involve including a library like this one including pre-rendering of a subset of routes, etc., that may not actually activate the library itself.
Fixes #826 
- Returns `false` for support checks on video formats when the DOM itself does not exist.
Code change is trivial so tests were not implemented (also, `document` cannot exist for the test to occur).
> fix: #826 depends on existence of DOM/document

- package-lock.json
- package.json
Saw an issue when running tests manually, caused by a bug in muxjs. This update fixes it.
> chore(package): update muxjs to 5.6.1 to fix small 708 caption issue

- src/master-playlist-controller.js
It's hard to find where loader stats methods are created because we do
it dynamically.
Add a comment with the full name of the loader stats methods so that
they can be searched directly.
> chore(mpd): add comment with full name of loader stats methods

- src/playback-watcher.js
- src/segment-loader.js
- src/sync-controller.js
- test/playback-watcher.test.js
- test/segment-loader.test.js
- test/sync-controller.test.js
- test/vtt-segment-loader.test.js
Timeline mappings should only be saved for the main loader. This is for multiple
reasons:
1) Only one mapping is saved per timeline, meaning that if both the audio loader
and the main loader try to save the timeline mapping, whichever comes later
will overwrite the first. In theory this is OK, as the mappings should be the
same, however, it breaks for (2)
2) In the event of a live stream, the initial live point will make for a somewhat
arbitrary mapping. If audio and video streams are not perfectly in-sync, then
the mapping will be off for one of the streams, dependent on which one was
first saved (see (1)).
3) Primary timing goes by video in VHS, so the mapping should be video.
Since the audio loader will wait for the main loader to load the first segment,
the main loader will save the …
> fix: only save timeline mappings for main loader

- src/master-playlist-controller.js
- src/playback-watcher.js
- src/ranges.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/master-playlist-controller.test.js
- test/playback-watcher.test.js
- test/ranges.test.js
- test/videojs-http-streaming.test.js
Tested using the issue from #823. I also tested that this code does not blacklist playlists with large content on slow network connections. IE throttle network to 10mb/s in chrome and select the 4k boat source.
1. `npm install mux.js@5.5.3` and use `https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8`. Skip to the middle of the video and change audio tracks. Before we would infinite download audio, now we blacklist until everything stops.
2. comment out `this.shouldSaveSegmentTimingInfo = false` in `vtt-segment-loader.js`. Run the axiom live stream, not that the text track is excluded after some time as it isn't making any progress.
3. Test with a playlist that has gaps to verify that nothing is excluded. 
4. Tested with a playlist that has one vtt for the …
> feat: Use playback watcher to watch when progress isn't being made

- scripts/index-demo-page.js
Fixes an issue the test page currently has on firefox, forces vhs to be used on the test page for safari.
> chore: fix demo page on firefox, always use vhs on safari

- README.md
- docs/supported-features.md
> docs: add supported features doc

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
Prevents a memory leak that we have right now, caused by not revoking urls that we create.
> fix: Use revokeObjectURL dispose for created MSE blob urls

- src/master-playlist-controller.js
- src/rendition-mixin.js
- test/master-playlist-controller.test.js
- test/rendition-mixin.test.js
Right now we don't have a great way to manually switch playlists without calling `blacklistCurrentPlaylist` and hoping for the best or using the renditions api to exclude all renditions that we don't want. This change allows us to pass a playlist into `smoothQualityChange_` and `fastQualityChange_` so that we can directly change to the playlist we want. It also adds playlist codecs to the rendition API.
> feat: Easier manually playlist switching, add codecs to renditions

- src/videojs-http-streaming.js
- test/playback.test.js
- test/videojs-http-streaming.test.js
Currently we don't narrow down supported codecs for drm sources. So sometimes we try to start a drm source with an unsupported codec and things don't work.
> fix: drm codec selection issues

- scripts/index-demo-page.js
Noticed that the globals were out of date on source switch.
> chore: keep window vhs/mpc up to date on source switch

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
Fixed issue  (#873) with MPEG-Dash MPD Playlist Finalisation during Live Play.
Stop `refreshXml_` if received `minimumUpdatePeriod` is equal to 0 (i.e. not present in updated mpd)
> fix: Fixed issue with MPEG-Dash MPD Playlist Finalisation during Live Play.

- src/videojs-http-streaming.js
- test/master-playlist-controller.test.js
- test/videojs-http-streaming.test.js
> fix: initialize EME for all playlists and PSSH values

- src/reload-source-on-error.js
- test/reload-source-on-error.test.js
Previously, we were getting the source from tech.currentSource_. This
only gets set when a source handler like VHS is used. However, because
VHS is in Video.js by default and the plugin is global, some people are
using this plugin for other sources as well.
There isn't a reason why we should be relying on tech.currentSource_
over player.currentSource() when we have access to the player in the
plugin.
Fixes videojs/video.js#6744
> fix: have reloadSourceOnError get src from player

- src/master-playlist-controller.js
- src/media-groups.js
- test/media-groups.test.js
This is most noticeable right now on safari on the hevc fmp4 stream that we have for testing. You can reproduce it in `main` by seeking around and force changing the representation to one with another codec:
```js
vhs.representations().forEach((r, i) => r.enabled(i ===49))
vhs.representations().forEach((r, i) => r.enabled(i ===53))
vhs.representations().forEach((r, i) => r.enabled(i ===20))
```
Usually it will fail with an append error, because we change the codec and then try to append old codec data. This happens because we previously waited until `mediachange` to `stopLoaders` for `audioLoader` but for the `mainLoader` we stop right away. This causes a race condition where old audio gets appended before the media has fully changed, but after codecs have. The fix here is to stop/pause …
> fix: stop alt loaders on main mediachanging to prevent append race

- src/media-segment-request.js
- src/segment-loader.js
- test/master-playlist-controller.test.js
Noticed that our fmp4/ts mixed content is failing. This is happening because we fire `trackinfo` on a change when we did not before. The trackinfo that we fire for the ts segment causes us to stall palyback because we wait for `audio`, but only ever receiver `video`/`combined` back from the transmuxer. The [fix for muxed fmp4 was only reporting `hasVideo`](https://github.com/videojs/http-streaming/blob/e0e497f7ca00aa061147e4dd005d03cb802f9cec/src/media-segment-request.js#L412). The fix for ts is exactly the same, we should not report `hasAudio` if the audio and video are muxed together or else we will wait for audio appends that will never come.
> fix: do not wait for audio appends for muxed segments

- package-lock.json
- package.json
- test/media-segment-request.test.js
Noticed while generating some aac content for tests using ffmpeg that we do not support aac content that does not have ID3 tags. This was fixed with mux.js@5.6.6 as mux.js did not recognize aac content without id3 tags as aac content.
> fix: support aac data with id3 tags with mux.js@5.6.6

- index.html
- scripts/index-demo-page.js
While looking into issues related to codec switching and representation/playlist changes I implemented local changes to select representations using the demo ui. I think this would benefit all of us, so I cleaned it up and wrapped it into a pull request.
> chore(demo): add a representations selector to the demo page

- src/source-updater.js
- test/segment-loader.test.js
It seems like ie 11 likes to error when using removeSourceBuffer, let's just say that it isn't supported and not use it.
> fix: do not use remove source buffer on ie 11

- src/master-playlist-controller.js
- test/master-playlist-controller.test.js
- test/videojs-http-streaming.test.js
Brings back code from 1.x where we exclude incompatible codecs. This time though we exclude by browser/muxer, rather than just browser.
> feat: exclude all incompatable browser/muxer codecs

- scripts/index-demo-page.js
- src/master-playlist-controller.js
- test/master-playlist-controller.test.js
1. Pause loading needs to call abort as well, or else we seem to still be able to continue requesting segments after an error. All of the segments will fail to append, but we will waste a lot of bandwidth.
2. We call pauseLoading after an exclusion to prevent the excluded playlist from appending a bad segment. 
1. When appending same-codec content appends don't really error, different codec content though does.
1. Go to the index page in main change renditions to the hevc renditions as fast as possible and notice an append error.
2. Try the same on this branch
> fix: pause/abort loaders before an exclude, prevent bad appends

- src/segment-loader.js
- test/segment-loader.test.js
This pull request does three things:
1. Always append an init segment after a `trackinfo` update. We do this because if the `trackinfo` causes a `changeType` we **have** to append an init segment or chrome will media error decode.
2. Check for individual segment trackinfo before appending and allow appending after trackinfo
3. Check for an abort after a trackinfo event is triggered, in the case where the type we are changing to is not supported.
> fix: always append init segment after trackinfo change

- scripts/sources.json
We put `com.widevine.alpha` instead of `com.microsoft.playready`
> chore: fix tears of steal playready on the demo page

- scripts/sources.json
- test/playback.test.js
The previous URL was https://vm2.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd. It seems like `vm2` was an old simulated livestream domain that's been deprecated for a while. The new version is http://livesim.dashif.org/.
> chore: update DASH stream urls

- docs/supported-features.md
- package-lock.json
- package.json
- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
- test/manifests/location.mpd
Depends on https://github.com/videojs/mpd-parser/pull/102
With it, I can see that we properly update the srcUrl internally based on the location, for example with a stream like https://livesim.dashif.org/livesim/startrel_-20/stoprel_20/timeoffset_0/testpic_2s/Manifest.mpd
TODO
> feat: support MPD.Location

- .github/ISSUE_TEMPLATE.md
Typo from `accesible` to `accessible`
> docs: Typo from accesible to accessible

- src/resolve-url.js
- src/videojs-http-streaming.js
This makes it so that users don't need to specify handleManifestRedirect themselves. It was originally defaulted to false because the option doesn't work on IE11 but it works everywhere else.
Makes streams like https://livesim.dashif.org/livesim/startrel_-60/stoprel_-20/timeoffset_0/testpic_2s/Manifest.mpd work without extra configuration.
> feat: default handleManfiestRedirect to true

- scripts/sources.json
- src/media-groups.js
- test/master-playlist-controller.test.js
- test/playback.test.js
When An audio group has the same uri as a main playlist, don't count it as an audio group. 
The code that I am using is from [this commit](https://github.com/videojs/http-streaming/commit/3cefde2c66ae7bfac8086b45d443502960bba844#diff-46e43d417013a9cfb72f6b3210979b63)
[I removed this code early on the the VHS 2 process](https://github.com/videojs/http-streaming/pull/469) as it was causing other issues, but after digging up some demuxed live streams I no longer see issues with live stream timeouts.
I created a source that replicates this issue and uploaded it next to some of our other test content. I also tested with a few of the demuxed live streams that we have and they all appear to work. It is likely that the live stream startup issues that I was seeing were fixed somewhere else.
> fix: audio groups with the same uri as media do not count

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
This fixes an issue where an MPD update can be missed if some media playlists are updated while the last playlist remains unchanged (see [here](https://github.com/videojs/http-streaming/blob/master/src/dash-playlist-loader.js#L71-L80))
In `updateMaster()`, update `noChanges` to default to `true`, and set it to `false` if any playlist is changed.
> fix: dash manifest not refreshed if only some playlists are updated

- src/dash-playlist-loader.js
- src/manifest.js
- src/playlist-loader.js
- test/dash-playlist-loader.test.js
- test/manifests/dash-swapped.mpd
This is particularly used in DASH as the `NAME` is set from the Representation's `ID` which is specified to be unique per period and that across periods, the representations with the same ID should be functionally equivalent.
This is important because in DASH, across periods, it's possible for Representations to be re-ordered, and we want to make sure that the reference doesn't get messed up when the period updates.
It still sets up a reference to the playlist via the old name but if the ordering is changed it'll reference the incorrect playlist as it does now.
TODO
> fix: use playlist NAME when available as its ID

- src/playback-watcher.js
- test/playback-watcher.test.js
- test/test-helpers.js
We are seeing a video underflow for demuxed fmp4 content. I think the main issue is timing related, but I have yet to narrow down the cause. While going through our code I noticed that we already detect video underflows for **muxed** content. I added code to detect **demuxed** video underflows so that we can fix those as well.
> fix: detect demuxed video underflow gaps

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
I run into issues where I am trying to play drm content but do not have the eme plugin. This causes the video buffer to increase but playback will never start because drm was never initialized. I propose that we trigger a player error in this case. If we don't want to go that far though we can just make this a warning.
> fix: Throw a player error when trying to play DRM content without eme

- src/playlist.js
- test/playlist.test.js
Currently we ran into an issue with `roundSignificantDigit` because it is rounding integer whole numbers when it seems like it was only made to round floats. This can cause us to download multiple duplicate segments on slow connections. Instead I propose that we only round by `TIME_FUDGE_FACTOR` here. This will prevent us from having to do any rounding at all.
Rounding a value of `2.111111` to `2.111112` is less than 1 milliseconds a very small change but rounding from `2.1` to `2.2` is 100ms. Both are possible with the current code.
All numbers are rounded up or down by 33 milliseconds
1. Cap the rounding at `TIME_FUDGE_FACTOR` for all numbers, but round less for longer floats. Not sure this one really makes sense as longer floats are not necessarily more accurate.
2. Don't round for …
> fix: use TIME_FUDGE_FACTOR rather than rounding by decimal digits

- src/master-playlist-controller.js
- src/segment-loader.js
- test/master-playlist-controller.test.js
- test/segment-loader.test.js
- test/videojs-http-streaming.test.js
mediaConfig_ and startingMedia_ are fairly poor names for variables, we should do better and rename them to something that can be easily understood. This pull request aims to do that. Originally this work would have been done as a part of #950 but this change might have a bigger impact than intended.
> Chore: rename mediaConfig_ and startingMedia_

- package-lock.json
- package.json
- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
This is part of a set of upcoming changes to add support for live DASH playback. Specifically, this PR differentiates the handling of 2 cases which were formerly conflated:
1. The `MPD@minimumUpdatePeriod` attribute has a _value of 0_, indicating that the MPD has no validity after the moment it was retrieved.
2. The `MPD@minimumUpdatePeriod` attribute is _absent_, indicating the MPD has infinite validity and will never be updated
- Update [`mpd-parser`](https://github.com/videojs/mpd-parser/pull/103) to allow us to identify case 2
- Make sure `updateMaster()` checks if a manifest's `minimumUpdatePeriod` value changes, and return the new manifest if so.
- Add handling for case 1: minimumUpdateperiod is 0 
- Continue refreshing manifests every `targetDuration`, per existing …
> feat: Update minimumUpdatePeriod handling

- src/dash-playlist-loader.js
This fixes a bug caused by an oversight in #942. If the `MPD@minimumUpdatePeriod` is 0 in the first dynamic MPD we load, we should use the media's target duration as the MPD refresh interval, however we need to wait until a playlist has been selected before we can know `DashPlaylistLoader.media().targetDuration`, otherwise we get a TypeError.
If the `minimumUpdatePeriod` is 0 and we haven't loaded a playlist yet, wait for `'loadedplaylist'` to setup the `minimumUpdatePeriodTimeout_`
> fix: MPD not refreshed if minimumUpdatePeriod is 0

- src/vtt-segment-loader.js
We should noop handleData in vtt segment loader so that any captions which we don't support the type of, such as `stpp.ttml.im1t` from `tears of steal widevine unified streaming` do not attempt to append to sourceBuffers and cause a player append error.
> fix: noop vtt segment loader handle data

- package-lock.json
- package.json
- src/segment-loader.js
`appendsdone` may cause an abort in segmentloaders which can then cause `pendingSegment` to be null **after** we just null checked it. Instead we should check if we have a `pendingSegment` then trigger appends done and see if an abort happens.
> fix: appendsdone abort and handle multiple id3 sections.

- package-lock.json
- package.json
- scripts/rollup.config.js
- src/videojs-http-streaming.js
Ideally we would be able to specify regex externals in videojs-generate-rollup-config, but we cannot currently. For now we will use [@rollup/plugin-replace](https://github.com/rollup/plugins/tree/master/packages/replace) to fix issues with downstream webpack builds caused by importing json directly.
> fix: inline json version

- src/master-playlist-controller.js
- src/segment-loader.js
- test/master-playlist-controller.test.js
This is a followup to #886. There, I noticed that if we get sustained bad network we will time out because we will an opportunity for earlyabort. At first, I tried working around by delaying earlyabort in that case (#966) but as I was getting that ready I kept finding edge cases that we needed to account for. Specifically, the issue is that we only run our ABR algorithm on `progress` and `bandwidthchange` events from the segment loader. This means that if the download stalls, we stop run our algorithm and will eventually stall playback. Instead, we should remove earlyabort altogether (f897dde) and set up an interval (currently 250ms) to re-run our ABR algorithm. This means that if the network becomes bad for a sustained period, we will drop down once the buffer allows us but if the …
> fix(experimentalBufferBasedABR): call selectPlaylist and change media on an interval

- scripts/sources.json
- src/media-groups.js
- src/segment-loader.js
- test/media-groups.test.js
- test/playback.test.js
Fixes an issue (not the only issue) with #977
caused by the fix in https://github.com/videojs/http-streaming/pull/952
> fix: only prevent audio group creation if no other playlists are using it

- src/playback-watcher.js
- test/playback-watcher.test.js
It's possible that a subtitle track will have segments without any text
in them depending on how the subtitles and captions were created.
Therefor, we should ignore it in the playback-watcher where we're
checking for excessive downloads.
> fix(playback-watcher): ignore subtitles

- src/config.js
- src/master-playlist-controller.js
> Note that this also effects the current non-experimental abr algorithm 
During low bandwidth situations continuing to download any segments over the video/audio segment is ill-advised as we need to get the buffer filled again ASAP. So when we get an early abort we have to abort all segment loaders to make way for the new playlist that is about to load, so that it can have priority.
Fixes #964
> fix: abort all loaders on earlyabort

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
I am working on refactoring the parsing logic in dash-playlist-loader. This is difficult because the logic is almost impossible to follow in the current state of the code. I tried a grand over-arching refactor and ultimately wasn't happy with it. Instead I am going to opt for smaller changes to get us towards what we want.
1. (this pull request) Add a property (isMaster_) to identify if the dash-playlist-loader is master. When masterPlaylistLoader is not passed into the constructor we know that the master playlist loader will be this one. We also shadow `this.masterPlaylistLoader` to `this` for master so that operations that update master always happen on `this.masterPlaylistLoader`. This simplifies a lot of the code and makes it much easier to understand. 
2. refactor parseMasterXml so …
> refactor: Add a better distinction between master and child dash loaders

- src/util/text-tracks.js
- src/vtt-segment-loader.js
- test/text-tracks.test.js
This is a replacement for #995, which was an attempt to revert a PR that resulted in WebVTT cues with identical time-intervals (which the spec allows) being removed from the cue list. However, simply reverting the change broke 608 captions, so another solution was required.
The main goals of this PR are to:
1. Make sure WebVTT cues are not removed from the TextTrackList just because they have the same time-intervals
2. Satisfy the original purpose of this [logic](https://github.com/videojs/http-streaming/blob/main/src/vtt-segment-loader.js#L368-L369) (originally [this](https://github.com/videojs/videojs-contrib-hls/pull/1219)) that I removed, which is to make sure any cues that "overlap" VTT segments (cues that are both the last cue of one segment and the first cue of the next segment) …
> fix: VTTCues with identical time intervals being incorrectly removed

- package-lock.json
- package.json
- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
~~The second pull request in our dash-playlist-loader refactor, based on #992~~ now merged
~~This pull request depends upon https://github.com/videojs/mpd-parser/pull/109~~ now released, and using that version.
1. Consider sidx in updateMaster so that playlists that had sidx added and thus haven't actually changed do not trigger a master update.
2. Only parse master xml once for a given xml string. Previously we parsed it 3 times for non-sidx and 4 times for sidx.
3. Unify some sidx and master playlist handling logic
> refactor: add sidx segments instead of reparsing

- scripts/sources.json
This pull request adds multiple sources that will be fixed by the following pull request/releases
1. fmp4/opus and fmp4/flac ~ currently in mux.js master, needs a release https://github.com/videojs/mux.js/pull/355
2. fmp4/aac currently works
3. ts with one valid audio/video codec but a bunch of invalid codecs too
4. sidx version 1 box dash. needs https://github.com/videojs/mux.js/pull/310
> chore: add multiple soon-to-work sources

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
Third and final dash-playlist-loader refactor.
Based on #994 
* Merge all master playlist loader request logic into `requestMaster_`
* Merge all sidx logic into `addSidxSegments_`
* Merge all error logic into `requestErrored_`
> refactor: unify sidx/master/error request logic

- package-lock.json
- package.json
- src/master-playlist-controller.js
- src/segment-loader.js
- src/source-updater.js
- src/videojs-http-streaming.js
- test/master-playlist-controller.test.js
- test/source-updater.test.js
- test/test-helpers.js
- test/videojs-http-streaming.test.js
Requires https://github.com/videojs/videojs-contrib-eme/pull/124
Wait for EME initialization before appending content. This is particularly important for Chrome, where, if unencrypted content is appended before encrypted content and the key session has not been created, a MEDIA_ERR_DECODE will be thrown once the encrypted content is reached during playback.
> Wait for EME initialization before appending content

- package-lock.json
- package.json
- Fixes issue with baseTime 0
- Initial support for CEA 708 captions
- Support for SIDX v1 boxes
- opus/flac support in fmp4 playlists
Closes #1001, fixes #909
> feat: update to mux.js 5.7.0

- src/dash-playlist-loader.js
After the dash playlist loader refactors the timeout for minimumUpdatePeriod is not set every time a refresh happens for master, as master isn't always changing. We should just set another timeout for minimumUpdatePeriod after triggering so that we can keep it going without worrying about updating it if its unchanged.
> fix: keep running the minimumUpdatePeriod unless cancelled or changed

- src/media-segment-request.js
fmp4 Tracks with id 0 are broken as we don't add their timescale to the init segment map.
> fix: track id 0 is valid

- src/segment-loader.js
- src/vtt-segment-loader.js
- test/segment-loader.test.js
Really small segments can mess with our ABR algorithm by not reflecting our bandwidth and throughput accurately for the majority of segments.
> fix: don't save bandwidth and throughput for really small segments

- src/master-playlist-controller.js
- src/playlist-selectors.js
Start the timer later, so we don't try to call `simpleSelector` without a playlist. However, we should add a null-check there just in case.
Fixes #1025
> fix(experimentalBufferBasedABR): start ABR timer on main playlist load

- src/segment-loader.js
- test/segment-loader.test.js
For HLS content, this will warn log for segments with an actual duration way over the target duration, and will debug log for segments a bit over the target duration.
> feat: log on mislabeled segment durations for HLS

- scripts/index-demo-page.js
If a user manually changes the url, the type may not be correct anymore.
We should clear it. Given that we auto-detect .m3u8 and .mpd types, it
shouldn't be a big deal and would cause less problems than the incorrect
type being present for the given source.
> chore(demo): clear type on manual source change

- scripts/sources.json
With the [recent update of mux.js to 5.7.0](https://github.com/videojs/http-streaming/pull/1014) many of the sources that I added in #1007 now work. Mark then as working. I also corrected a typo in one of the sources that is still not working.
> chore: mark many more sources as working

- test/media-segment-request.test.js
Basically tests after test in media segment requester can fail. It just so happens that those are our playback tests. They fail because we have a `currentTransmux` in the `SegmentTransmuxer` after that gets disposed everything works!
> test: clear segment transmuxer in media segment request tests

- README.md
- package-lock.json
- package.json
- src/master-playlist-controller.js
- src/segment-loader.js
Add cc708 as a VHS option to turn off 708 captions.
This PR depends on https://github.com/videojs/mux.js/pull/365
> feat: add flag to turn off 708 captions

- scripts/sources.json
Noticed we were missing a legacy avc source so I created one and added it. We also need to add the ll-hls stream for upcoming work so I added that as well.
> chore: add ll-hls source and legacy avc source

- index.html
- package-lock.json
- package.json
- scripts/index-demo-page.js
- scripts/rollup.config.js
- src/decrypter-worker.js
- src/master-playlist-controller.js
- src/segment-loader.js
- src/transmuxer-worker.js
- test/loader-common.js
- test/media-segment-request.test.js
- test/segment-transmuxer.test.js
- test/transmuxer-worker.test.js
I wrote [rollup-plugin-worker-factory](https://github.com/brandonocasey/rollup-plugin-worker-factory) for Mux.js so that we could support nodejs workers and browser workers using the same plugin. It has side benefits of:
1. not needing a separate build target for workers that has to run before other builds
2. We can share a rollup cache between the worker and main builds
3. Worker code doesn't have to be wrapped in a strange function or export anything.
4. The new rollup plugin is much more readable than our current plugin.
5. We can support add a debug build for web workers that run in the same thread and not a WebWorker blob for debugging.
> chore: better worker build

- src/segment-loader.js
- src/segment-transmuxer.js
- test/media-segment-request.test.js
- test/segment-loader.test.js
- test/segment-transmuxer.test.js
- test/transmuxer-worker.test.js
So this is somewhat of a bigger issue then I originally realized when I found an issue in tests for #1043 . The segmentTransmuxer stores a global cache of the currentTransmux and transmux queues. This causes a few issues:
1. Separate audio/video transmuxes will bottleneck on another
2. When running two or more videos on a page each video has a chance to bottleneck all the others with it's transmuxQueue and currentTransmux
3. Tests/dispose is flakey because mediaSegmentRequest sets currentTransmux/transmuxQueue but only segmentLoader disposes it.
Store the transmuxQueue and currentTransmux on the transmuxer that is being used rather than keeping a global list.
> fix: store queue and current transmux on transmuxer instead of global

- src/media-segment-request.js
- src/segment-loader.js
- src/segment-transmuxer.js
- test/segment-transmuxer.test.js
Previously, when the end of a timeline was reached (i.e., the last
segment in a given timeline was appended), `endTimeline` would be
called, but the loader would not wait for the event to finish. This
lead to issues where segment information came back after a segment is
considered done with processing, and segment information could be
dropped. This fix waits for the `endedtimeline` message from the
transmuxer before it considers the transmux complete.
> fix: wait for endedtimeline event from transmuxer when reaching the end of a timeline

- src/xhr.js
- test/videojs-http-streaming.test.js
It is not currently possible to override or add any custom XHR logic at initialization, since the `xhr()` method is not exposed on the tech until the source is set ([see](https://github.com/videojs/http-streaming/blob/main/src/videojs-http-streaming.js#L1153)) and uses a reference to the [original `videojs.xhr()`](https://github.com/videojs/http-streaming/blob/main/src/xhr.js#L77).
Although it is unadvisable in most cases (as mentioned in the docs), it is still useful to have the ability to do it, and the existing `beforeRequest()` hook is insufficient in many cases.
- Substitute a custom `videojs.Vhs.xhr` function for `videojsXHR`, if it is provided
- This PR does not add any documentation, as I wasn't sure if it is something we want to document
> feat: Allow xhr override globally

- index.html
- scripts/index-demo-page.js
- src/master-playlist-controller.js
- test/videojs-http-streaming.test.js
We don't do a very good job respecting `preload=none` on the video element because even with preload=none we still download the manifests and potentially waste bandwidth with videos that never get played. We should prevent that when preload is set to `none`.
> fix: do not request manifests until play when preload is none

- test/segment-loader.test.js
> test: for IE11, add colon to timezone in Date strings of PDT mapping tests

- src/master-playlist-controller.js
- src/segment-loader.js
- test/master-playlist-controller.test.js
- test/segment-loader.test.js
Previously, if there wasn't any current media info in the loader, then a
remove of buffered contents would not be processed. This would
intuitively make sense, as if there wasn't current media info, then in
theory there shouldn't be any buffered contents. However, it is possible
for there to be buffered contents without current media info in the event
of a non destructive rendition switch. This was noticed when switching
renditions, expecting a fast quality change to clear the contents and
continue playback at a new rendition. Sometimes the remove wouldn't
happen, so the content would continue to play back the old buffered
content from a different rendition. This fix instead allows the removes
so long as there is starting media info (which is available after first
segment download).
> fix: allow buffer removes when there's no current media info in loader

- src/vtt-segment-loader.js
fix: sometimes subtitlesTrack_.cues is null
sometimes subtitlesTrack_.cues is null
I added null check code.
- [v] Feature implemented / Bug fixed
> fix: sometimes subtitlesTrack_.cues is null

- index.html
- scripts/index-demo-page.js
Uses sourceset to mirror the source that was set via `player.src` in the ui so that it will be saved on page reload!
> chore: mirror player.src on the demo page demo page

- src/dash-playlist-loader.js
- src/playlist-loader.js
- test/dash-playlist-loader.test.js
- test/manifests/dashByterange.mpd
Currently dash content goes off of the `number` attribute for segments to determine the mediaSequence. This is problematic as the first segment is almost always listed as `1`. So in essence when we request the playlist again the media sequence will be the same, and likely the amount of segments will be the same, so we will determine that this playlist update didn't update anything at all.
You can currently see this issue with the `Unified Streaming Live DASH` source. Eventually we will get into a state where the playlist isn't seen to be refreshing, even though the underlying segment uri's are changing every request.
> fix: live dash segment changes should be considered a playlist update

- .github/workflows/ci.yml
- scripts/rollup.config.js
Add a minified test bundle for testing to prevent issues like what we saw in v2.6.0
> test: add playback-min as a unit test type

- src/playback-watcher.js
- test/playback-watcher.test.js
Fixes #1084 . There is an edge case that is exposed when a gap exists at the beginning of the stream and no content is buffered by the time the first `waiting` event has emitted. This leaves the player in a state where it's no longer checking for playback stalls (or gaps).
As mentioned in the linked issue, we have decided to proceed by checking for stalls when the first `play` event is emitted.
- [ x] Feature implemented / Bug fixed
- [ x] Unit Tests updated or fixed
> Skip over playback gaps that occur in the beginning of streams

- src/dash-playlist-loader.js
- src/master-playlist-controller.js
Add a reason for exclusions and skip `playlist-unchanged` if we have already seen it.
> fix: Add exclude reason and skip duplicate playlist-unchanged

- src/playback-watcher.js
- test/playback-watcher.test.js
This is a follow-up fix for #[1084](https://github.com/videojs/http-streaming/issues/1084). @gesinger noticed an additional edge that's exposed when a new source is loaded via `player.src()` while the player was playing. This led to our `play` event handler not being called since it was wrapped by a check to ensure the player was in a paused state.
Additionally, I cleaned up a couple of tests by relying on Player API instead of firing HTML5Media events. This ensures the test more closely follows playback behavior in a production environment.
Removed the condition around the play event listener in PlaybackWatcher. Since we're using `one` and not `on`, I expect this change to be safe and not cause gaps to be skipped at irregular intervals (a test was also added in my last change to ensure …
> Monitor playback for stalls due to gaps in the beginning of stream when a new source is loaded

- index.html
- package-lock.json
- package.json
- scripts/index-demo-page.js
- src/manifest.js
- src/media-segment-request.js
- src/playlist-loader.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/loader-common.js
- test/segment-loader.test.js
- test/test-helpers.js
Implements support for EXT-X-PART and EXT-X-PRELOAD-HINT
Requires https://github.com/videojs/m3u8-parser/pull/137
* ~~Use `#EXT-X-PART-INF`, query parameters for delta updates, `#EXT-X-SERVER-CONTROL`, and `#EXT-X-SKIP`~~ #1079 
* ~~Use `#EXT-X-PRELOAD-HINT` aka `preloadSegment` on the manifest~~ #1078 
* How would we use `#EXT-X-RENDITION-REPORT` when switching renditions? Is it only relevant in the context of delta updates?
> feat: use EXT-X-PART for LL-HLS

- .github/workflows/ci.yml
Should prevent codecov links from being broken.
> chore: never skip coverage

- package-lock.json
- package.json
Update to mux.js 5.11.0, supports parsing more mp4 boxes.
> chore: update to mux.js@5.11.0

- package-lock.json
- package.json
- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
Requires https://github.com/videojs/mpd-parser/pull/123
Fixes our `Angel One - Widevine, fmp4, webm, subs, alternate audio tracks` and i'm sure it fixes others.
> fix: Only add sidxMapping on successful sidx request and parse.

- src/master-playlist-controller.js
- test/master-playlist-controller.test.js
- test/playback-watcher.test.js
- test/videojs-http-streaming.test.js
Switch all `this.masterPlaylistLoader.media_` calls to `this.switchMedia_` which will log the cause behind the switch as a triggered usage event.
> feat: usage on rendition change

- package.json
Trying out marking vjs as a peer dep.
I'll probably do a pre-release from this branch and then a pre-release of Video.js as well to see how things work.
> feat: mark Video.js as a peer dependency

- docs/supported-features.md
- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
To test, [encrypted video creator](https://github.com/gesinger/encrypted-video-creator) can be used to create three streams with the following options:
```bash
$ npm run start -- --source [some video].mp4 --destination [some video]-audio-and-video-widevine --key-system widevine
$ npm run start -- --source [some video].mp4 --audio-only --destination [some video]-audio-only-widevine --key-system widevine
$ npm run start -- --source [some video].mp4 --video-only --destination [some video]-video-only-widevine --key-system widevine
```
> fix: support automatic configuration of audio and video only DRM sources

- scripts/sources.json
- src/master-playlist-controller.js
- src/media-groups.js
- src/playlist-selectors.js
- src/playlist.js
- src/rendition-mixin.js
- test/master-playlist-controller.test.js
- test/media-groups.test.js
- test/playlist-selectors.test.js
- test/playlist.test.js
- test/rendition-mixin.test.js
Allows audio only playlists to change audio tracks. IE an audio only playlist can change from english to spanish correctly now. Would be good to get https://github.com/videojs/mpd-parser/pull/123 in with this.
> fix: Handle audio only audio track change correctly

- src/playlist-loader.js
I guess I missed one of the `llhls` -> `exerimentalLLHLS` changes in `playlist-loader.js`
> fix: experimentalLLHLS option should always be passed

- .github/workflows/ci.yml
- scripts/karma.conf.js
We can really run our tests in chromium as we require basic media types to be supported, which chromium does not support.
> chore: dont run tests on chromium

- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
Previously, for DASH, pausing a media loader would end up pausing the
main loader as well (via removal of the main loader's minimum update
period). For live streams which required manifest refreshes, this meant
that on media changes, the main loader would be paused and sometimes
never resumed.
This change ensures that when a media loader is paused it won't remove
the main loader's minimum update period timeout.
In addition, a change was made so that loading a main DASH playlist
loader recreates a minimum update period timeout if the main DASH loader
was previously paused (and the timeout cleared).
> fix: don't clear DASH minimum update period timeout on pause of a media loader

- package-lock.json
- src/manifest.js
- src/media-groups.js
- src/playlist-loader.js
- test/dash-playlist-loader.test.js
- test/manifest.test.js
- test/media-groups.test.js
Fixes issues with rendition switching on audio only hls media.
> fix: add master referenced id/uri audio playlists. Add playlists to hls media groups

- src/segment-loader.js
- test/segment-loader.test.js
Only append init segments on change.
> fix: only append init segment on change

- src/media-groups.js
- test/media-groups.test.js
Although the audio status is set in onTrackChanged for media groups, and
the function is called when the media groups are first set up, the track
is not always considered changed. This means that for demuxed audio, the
main loader may still think it should be using its own audio itself,
leading to issues when crossing discontinuities (i.e., the main loader
will cross the discontinuity before waiting for the audio loader to be
ready, leading to audio timestamps that aren't correct).
This change ensures that the audio status is set on setup, regardless of
whether the track is considered changed. Subsequent changes are handled
in onTrackChanged.
> fix: set audio status on loaders when setting up media groups

- test/segment-loader.test.js
seems like coverage is failing on ci right now, trying to fix it.
> chore: fix coverage ci

- README.md
- package-lock.json
- package.json
- src/media-groups.js
- src/util/text-tracks.js
- test/loader-common.js
- test/master-playlist-controller.test.js
- test/media-groups.test.js
- test/text-tracks.test.js
Add an option for caption services metadata in case the user wants to specify labels for 608/708 captions, override the ones provided in the manifest, or needs to add more information like character encoding (this isn't currently available but will be added some time in the future).
For HLS, an `EXT-X-MEDIA` tag can be specified with an `INSTREAM-ID` attribute. We already support this. https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-08#section-4.4.6.1
This PR updated mpd-parser which uses the ANSI 214 supplamental spec section 7.2 to parse out the same information from MPD files. https://github.com/videojs/mpd-parser/pull/131.
Adds a property called `captionServices` which has properties of the caption service IDs like `CC1` or `SERVICE1` and allows a user to specify a …
> feat: Caption services (608/708) metadata

- src/master-playlist-controller.js
- test/master-playlist-controller.test.js
Set a default for the option MaxPlaylistRetries (default should have been Infinity, seems like there was a bad merge)
> Default maxPlaylistRetries to Infinity

- scripts/rollup.config.js
`debugger;` statements are currently being stripped.
> chore: do not strip debugger statements

- package-lock.json
- package.json
see https://github.com/videojs/mux.js/pull/390
> fix: Prevent skipping frames in adts data via mux.js 5.11.3

- package-lock.json
- package.json
- src/media-segment-request.js
- src/segment-loader.js
- src/segment-transmuxer.js
- src/transmuxer-worker.js
- test/media-segment-request.test.js
- test/segment-loader.test.js
- test/transmuxer-worker.test.js
Log debug/warn/error from the transmuxer.
https://github.com/videojs/mux.js/pull/391
> chore: use transmuxer debug/warn/error events to the debug log

- test/master-playlist-controller.test.js
- test/media-segment-request.test.js
Currently leaking some web workers between tests that we need to cleanup.
> test: cleanup transmuxers in tests

- src/master-playlist-controller.js
- src/segment-loader.js
- test/loader-common.js
This prevents an issue shown via the test that I added. Mainly that a playlist change that happens before we append data from a `pendingSegment_` will cause reset `this.currentMediaInfo_` to be null. Thus causing `handleData_`'s call to `hasEnoughInfoToAppend_`  to throw on `this.currentMediaInfo_.hasAudio`
> fix: Use segmentInfo.trackInfo to get segment information.

- src/manifest.js
- src/master-playlist-controller.js
- test/manifest.test.js
- test/master-playlist-controller.test.js
Fixes Song - ts Audio only which doesn't work because it has invalid media groups (without uris)
> fix: do not add placeholder properties for AUDIO groups without a uri

- package-lock.json
- package.json
Correctly detects mp4's that start with moof/moov instead of ftyp/styp.
> fix: update vhs-utils to correctly detect mp4 starting with moof/moov

- test/configuration.test.js
- test/loader-common.js
- test/playback-watcher.test.js
- test/segment-loader.test.js
- test/source-updater.test.js
- test/test-helpers.js
- test/videojs-http-streaming.test.js
Chrome 92 requires media elements to be torn down completely before they are removed from memory. This includes unsetting the src property and removing the src attribute. 
This is only an issue when a lot of players are created and disposed on a page. For us this mostly happens in tests.
The error in question:
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
> test: fix tests in chrome 92 by disposing media elements/ blob url

- index.html
- scripts/index-demo-page.js
- src/master-playlist-controller.js
- src/playlist-selectors.js
- src/videojs-http-streaming.js
- test/master-playlist-controller.test.js
- test/playlist-selectors.test.js
- test/videojs-http-streaming.test.js
Simplify and improve our resolution selection by selecting the closest resolution to the player, rather than using one larger or the exact size.
> feat: add experimental pixel diff selector behind a flag

- index.html
- scripts/index-demo-page.js
- src/master-playlist-controller.js
- src/playlist.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/playlist.test.js
Remove TIME_FUDGE_FACTOR from our calculations and just use manifest values.
> feat: Add experimentalExactManifestTimings which forgoes TIME_FUDGE_FACTOR during segment choice

- package-lock.json
- package.json
- test/playback.test.js
This is done via an update to version v0.18.0 of mpd-parser. see the [mpd-parser changelog](https://github.com/videojs/mpd-parser/blob/main/CHANGELOG.md)
Fixes sources like `Axinom Clear MultiPeriod - DASH, 4k, HEVC`
> fix: Generate the correct number of segments for segment template multi period dash

- scripts/index.js
- scripts/old-index.js
Prevents the issue where one of the data manifests is loaded as the first source instead of bipbop.
> chore: consistent source selection on demo start

- .github/workflows/github-release.yml
- package-lock.json
- package.json
Automates the github release changelog process.
> chore: add a github-release github action

- src/master-playlist-controller.js
- src/playlist-loader.js
- test/master-playlist-controller.test.js
- test/playlist-loader.test.js
Right now for live hls streams we can be stuck buffering even though we should have recovered because we don't attempt to retry requests. You can reproduce this:
1. Select `Unified Streaming Live HLS` 
2. Play
3. Set network to offline in dev tools
4. Wait for the player to stall
5. Set network back to normal in dev tools
6. Player will never recover
This happens because we exclude and pause the current playlist loader when it fails a request.  Then we switch to same playlist again and since it is the same playlist we don't try to request it again. So now we have no mediaUpdateTimeout and we did not request the playlist again.
1. We need a way to make sure that we start a mediaUpdateTimeout in `media`
2. We need mediaUpdateTimeouts to create media update timeouts 
3. We do not need to …
> fix: Keep media update timeout alive so live playlists can recover

- index.html
- scripts/index.js
- scripts/netlify.js
* Adds back in the run tests link (which is removed on netlify).
* Correctly disposes of stats on player dispose.
* Defaults to the new liveui 
* Saves the state of `player.muted()` to the test page state so that muting/unmuting the player is saved across reloads.
* Moves the preloaded source dropdown to the top of the form
> chore: various demo page fixes and enhancements

- src/videojs-http-streaming.js
Only register our reloadSourceOnError plugin once.
See https://github.com/brightcove/player-loader/issues/78
> fix: only register reloadSourceOnError once

- src/playback-watcher.js
- test/playback-watcher.test.js
In our current code we run `fixesBadSeeks_()` on tech waiting and our emulated tech waiting. This is problematic because at the time of tech waiting we won't have removed content from our segment loaders buffers. This means that any seek backwards within `targetDuration` will be skipped as a gap.
Example:
```
1. seek to 300 tech waiting fires, but there is nothing in the buffer at this time.
2. seek back to 290, tech waiting fires and we have buffer starting at 299s
3. playback watcher calls `fixedBadSeeks_` and determines that there is a gap from 290-299 as we have yet to append content.
4. playback watcher skips to 299
```
Previously we check to see if an append had happened by checking the buffer, but that isn't specific enough as large target durations will have issues as seen above. …
> fix: Only check for bad seeks after seeking and an append

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/master-playlist-controller.js
- src/segment-loader.js
Complementary Mux.js PR: https://github.com/videojs/mux.js/pull/398
The 708 implementation of mux will soon support multibyte character encodings, so this PR adds a way to pass the option to the transmuxer. using the existing `captionServices` options block.
> feat: Add ability to pass encoding value for 708 captions via captionServices

- src/sync-controller.js
- test/sync-controller.test.js
The browser tab running video.js would show a "Page Unresponsive" dialog in Chrome when the EXT-X-MEDIA-SEQUENCE tag increased by a large number between subsequent m3u8 files. This happened because the saveExpiredSegmentInfo function was iterating over this large number.
This behaviour was raised in [issue 1197](https://github.com/videojs/http-streaming/issues/1197)
The proposed solution is to avoid the browser becoming unresponsive by only iterating over the media sequence difference if it is within a reasonable threshold. 
To determine a reasonable threshold, I looked at Apple's ["Live Playlist (Sliding Window) Construction" page](https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/live_playlist_sliding_window_construction) which …
> Pr for media sequence

- README.md
- index.html
- scripts/index.js
- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
We've found that the player's bandwidth estimations provide lower-than-expected values when a particular segment is encoded with a low bitrate relative to other segments in its lane. This is a fairly common phenomenon when a live stream is using a variable bitrate encoding strategy and is broadcasting a static scene (e.g a slide in a slideshow). We believe that this issue is further exacerbated by two factors:
1. Segment size - Vhs estimates bandwidth by measuring how many bits were downloaded in a segment and how long, in seconds, it took to download those bits. This estimate factors in network-layer overhead which means that as the number of bits in a segment decreases (either due to bitrate or segment size), the impact that network overhead has on the bandwidth estimate increases
2. …
> Add an option to calculate bandwidth by using Chromium's networkInfo API

- test/videojs-http-streaming.test.js
The stubbing of networkInfo doesn't play nicely with ie11 which complains with the following message: `Assignment to read-only properties is not allowed in strict mode`. After speaking with Gary, we've decided to skip these tests in IE.
> Don't run networkInfo tests against ie11

- package-lock.json
- package.json
- src/segment-loader.js
- src/xhr.js
- test/segment-loader.test.js
- test/videojs-http-streaming.test.js
- test/xhr.test.js
* https://github.com/videojs/mux.js/pull/383
* https://github.com/videojs/mpd-parser/pull/135
> fix: mp4 sources that use bigint numbers

- src/master-playlist-controller.js
This removes a check for hasCreatedSourceBuffers that short circuited
onSyncInfoUpdate_. It also adds a comment about how to add the check
in the future, as a simple change of truthiness leads to other issues
in playing back a live stream.
> fix: fix seekable not updating after the first change for live streams

- package-lock.json
- package.json
- src/dash-playlist-loader.js
- test/dash-playlist-loader.test.js
- test/manifests/dash-live.mpd
In order to support the new mpd-parser API, whenever a DASH manifest
refreshes, the prior parsed manifest object needs to be passed in as
`previousManifest`. This change adds support for that.
NOTE: this is to support an upcoming feature in mpd-parser:
videojs/mpd-parser#152
> feat: use new mpd-parser API for handling live DASH refreshes

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
If a waitingforkey event is fired, try to set up new key
sessions, as the manifest may have new key information.
> feat: set up required key sessions on waitingforkey event

- test/videojs-http-streaming.test.js
> test: fix failing IE11 test due to late initialize of EME keys

- package-lock.json
- package.json
> fix(package): update mux.js to 6.0.1

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
> fix: clarify hls option deprecation warning

- src/playlist-loader.js
- test/playlist-loader.test.js
On a live playlist with media groups, subsequent fetches of the media playlist overwrite the playlist attributes with an empty object. This affects part of the rendiiton selection flow, including the audio only test. On an audio-only stream this impacts playback, as no audio only stream is found. This can result in cycling through the renditions, playing an unnecessarily low rendtion, or for streams with manifest redundancy, that playback stops.
Updates th playlist with the merged playlist rather than the unmodifed newly parsed playlist. This should have been the behaviour already.
> Fix: retain playlist attributes when refreshing live media playlists

- package.json
This adds ^8 in addition to ^7 for the dep and peerDep version ranges.
BREAKING CHANGE: remove ^6 from the dependency version ranges.
> fix: add Video.js 8 to the dep version range

- package-lock.json
- package.json
- scripts/karma.conf.js
- test/vtt-segment-loader.test.js
This updates the default [browserslist](https://github.com/videojs/babel-config/blob/main/es.js#L6-L19) used by babel. It drops support for some older browsers including IE 11. This also removes the `browserslist` in `package.json` so we use the default list from `@videojs/babel-config` (linked above).
**NOTE**: Merge with BREAKING CHANGE header.
> chore: Update generate-rollup-config to drop older browser support

- test/playback.test.js
The current live DASH playback test source uses a source where segments
are referenced by a SegmentTemplate and duration, but the server
doesn't have time syncing and appears to be about two minutes behind
local time. This leads to requests for segments beyond expected and
occasional failures.
Until that issue is fixed in VHS, switch to a live source that uses
SegmentTemplate, to be a more reliable basic live DASH playback test.
> test: change source for live DASH playback test to fix test failures

- src/master-playlist-controller.js
Whenever a playlist is excluded for any reason, we pause the `masterPlaylistLoader` and never restart it. We have noticed this causing timeouts with live DASH playback which relies on regular MPD refreshes.
If, for example, a single MPD or segment request fails for whatever reason, the `minimumUpdatePeriod` timeout [gets cleared](https://github.com/videojs/http-streaming/blob/main/src/dash-playlist-loader.js#L531) permanently, which halts any further MPD refreshes. This is a side-effect of `blacklistCurrentPlaylist()` , which gets called on all MPL and MSL errors. The MPC eventually picks up on the fact that the MPD is no longer updating and starts a cascade of futile [playlist switches](https://github.com/videojs/http-streaming/blob/main/src/master-playlist-controller.js#L644-L651) which …
> fix: Restart masterPlaylistLoader after media change

- src/master-playlist-controller.js
- src/segment-loader.js
- test/loader-common.js
- test/master-playlist-controller.test.js
Previously, if there was a segment timeout and `experimentalBufferBasedABR` was set to `true`, then the main segment loader would stay in a `READY` state and never resume loading segments. This is because the buffer based ABR path doesn't follow the same flow as non buffer based ABR, where a new playlist would be loaded immediately and it would trigger a load. Buffer based ABR may determine that no rendition change should be made, despite the timeout, leading to nothing happening. This change makes the call to load explicit, but only for buffer based ABR on timeouts.
This addresses https://github.com/videojs/http-streaming/issues/1287
* Updated test to show that `experimentalBufferBasedABR` does make a playlist selection on `bandwidthupdate`
* Updated test to remove warning logged on a …
> fix: resume loading on segment timeout for `experimentalBufferBasedABR`

- src/dash-playlist-loader.js
- src/manifest.js
- test/dash-playlist-loader.test.js
Fixes [Linear DASH SSAI Label Issue](https://github.com/videojs/http-streaming/issues/1351)
Linear multi-period DASH with `<Label>` elements that roll in and out of continuous `AdaptationSet`s cause the stream to stall because we use the value of the `<Label>` as the key for the `mediaGroups.type.group.<labelKey>` object _and_ the associated mediaGroup group/playlist ID. When the manifest updates and reaches the period either with a `<Label>` or omitting the `<Label>` we can no longer access that media group or playlists to update the playlist as we rely on the labelKey set from the previous manifest/period to look for new segments in the update.
- Change the way we create groupIDs for mediaGroup playlists to allow for DASH playlists to use the representation ID rather than the label from …
> fix: Linear DASH multiperiod label issue

- src/playlist-controller.js
- src/videojs-http-streaming.js
- src/vtt-segment-loader.js
- test/playlist-controller.test.js
- test/videojs-http-streaming.test.js
- test/vtt-segment-loader.test.js
We have a bug with default options setup for HLS in-manifest VTT in chrome iOS (and I assume other non-safari Webkit-based iOS browsers). The problem is that we do not load `vtt.js`, but we use `VHS` to handle playback. `vtt-segment-loader` implicitly depends on `window.WebVTT.Parser`. Since `vtt.js` is not loaded - `window.WebVTT` is `undefined`. It means that we are not able to parse received VTT cues.
- Do not override native for all iOS/iPadOS browsers by default.
- Add fallback logic to load `vtt.js` in `vtt-segment-loader` if we do not have it loaded. (eg: force `overrideNative` option case).
- Add exception guard with a specific error message in case we call parse but still do not have vtt.js loaded for any reason.
- Fix/Add tests to cover all listed changes.
> **Note**
> Tested …
> Fix: In-manifest VTT iOS MSE issue

- package-lock.json
- package.json
Updating mux.js to 6.3.0 to provide the emsg probe functions for [this PR](https://github.com/videojs/http-streaming/pull/1370) which will add emsg ID3 tag support to VHS.
Changing the version of mux.js used from 6.2.0 to 6.3.0.
> chore(package): update mux.js to 6.3.0

- src/master-playlist-controller.js
- src/segment-loader.js
- test/master-playlist-controller.test.js
We have a race condition issue that breaks playback during quality switch:
Here is a visual representation of the race condition:
As you can see from the visual representation, we have a pending segment request which is from the previous playlist, because the `seeking` event kick-starts the segment loader before we have a new playlist loaded. But we receive `trackInfo` after the new playlist is loaded. That means that during codec calculation it will get codecs from the new playlist, while the segment loader is about to append a segment from the previous one. Because initialization data is not added and codecs do not match with the source buffer's current codecs setup - the source buffer fails to append this segment.
The problem is reproducible mainly with CMAF HLS since the transport …
> Fix: CMAF HLS. Source buffer change type is called with wrong codecs sometimes when append segment without init data because of a race condition.

- .github/workflows/github-release.yml
- .github/workflows/release.yml
- COLLABORATOR_GUIDE.md
add npm publish step for release workflow
update release documentation
NOTE: `NPM_TOKEN` should be added to the repo secrets.
> chore: npm publish for release workflow

- src/media-segment-request.js
- src/transmuxer-worker.js
- test/media-segment-request.test.js
Currently VHS does not support passing ID3 frames to the text track from fmp4 segment emsg boxes. With some [additional parsing from mux.js](https://github.com/videojs/mux.js/pull/426) and this PR, this enables passing parsed ID3 frame data to the player `textTracks_` for use as timed metadata.
Adding a new function to the `transmuxer-worker` that calls `getEmsgId3` on the transmuxer and returns parsed ID3 frames. Calling the worker function and passing the ID3 frames to the `id3Fn` passed in from the mediaSegmentRequest.
> ~Note: This is blocked by the work in the transmuxer being released and integrated. See: https://github.com/videojs/mux.js/pull/426~
Changes are integrated into VHS see PR: https://github.com/videojs/http-streaming/pull/1372
References: …
> feat: add fmp4 emsg ID3 support

- package-lock.json
- package.json
Update the mpd-parser version to 1.1.0
Change the `mpd-parser` version in the package.json to `^1.1.0`
> chore: update mpd-parser to 1.1.0

- package-lock.json
- package.json
Fixes #1353
- Updates the version of Video.js installed in the `package-lock.json` to 8.x. This resolves issues stemming from having two different VHS dependency trees present.
- Updates videojs-contrib-quality-levels dev-dep to 3.x.
- Adds `@babel/ci` and `@popperjs/core` as dev-deps because they are required by other things in the dev-dep tree.
> chore(package): update dependencies to de-dupe m3u8-parser in the tree

- src/media-segment-request.js
- test/media-segment-request.test.js
Fixes https://github.com/videojs/http-streaming/issues/1379
Change the order of nested callbacks to the transmuxer to allow for fmp4 audio EMSG id3 metadata probing.
> fix: allow audio fmp4 emsg probe

- README.md
- index.html
- scripts/index.js
- src/media-groups.js
- src/videojs-http-streaming.js
- test/media-groups.test.js
- test/playlist-controller.test.js
Proposal to introduce a new `useForcedSubtitles` option to access forced subtitles when available.
Currently, VHS ignores forced subtitle tracks. This behavior makes it impossible to access such subtitles, when available, from `player.textTracks`.
As a result, content with occasional foreign language dialogue cannot be translated, forcing the user to enable subtitles for the entire playback time.
Referring to the question asked in the [Apple Developer Forums](https://developer.apple.com/forums/thread/43424). Forced subtitles, if available, should be displayed automatically either according to the system language or the selected audio language. This seems to be confirmed by the [Advice about subtitles](https://developer.apple.com/library/archive/releasenotes/AudioVideo/RN-AVFoundation/index …
> feat: Add an option to support forced subtitles

- .github/ISSUE_TEMPLATE.md
- README.md
The doc example was confusing, leading some people to including a VHS separately. Makes it clearer that including the VHS script shouldn't be necessary, and when so to use the core video.js.
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.
Please list the specific changes involved in this pull request.
> fix(docs): Remove confusion around including VHS separately

- src/segment-loader.js
- test/segment-loader.test.js
id3 cues are not added correctly to audio-only streams, as the test for an audio-only stream is broken. `videoTimestampOffset()` will never be `null` as it defaults to `0`, so the audio offset is not used.
Uses the `videoTimestampOffset()` when `segmentInfo.trackInfo.hasVideo` is `false` rather than when `videoTimestampOffset()` is null
Fixes #130 
- Open the [deploy preview](https://deploy-preview-1386--videojs-http-streaming.netlify.app/) and https://videojs-http-streaming.netlify.app to compare.
- In each console, add
```
const printCueData = (cues) => {
Array.from(cues).forEach((cue) => {
if ("value" in cue && cue?.value?.data) {
const value = new TextDecoder()
.decode(cue.value.data)
.replace("\x03", "")
.replace("\x00", "");
console.log({
value,
start: cue.startTime,
end: …
```
> fix: use audio offset for id3 with audio-only

- README.md
- src/videojs-http-streaming.js
- src/xhr.js
- test/videojs-http-streaming.test.js
- test/xhr.test.js
This PR would add xhr request and response hooks via an `onRequest(callback)` and `onResponse(callback)` API. The user can add as many unique hook callbacks as they want, and they will be called in the order they were added before the request and after the response is received respectively. The user can un-register these callbacks via the `offRequest(callback)` and `offResponse(callback)` API. The callback functions can take the following parameters:
- `onRequest` callbacks will pass the xhr `request` Object to the callback.
- `onResponse` callbacks will pass the xhr `request, error, and response` Objects to the callback in that order.
In addition, the user can use both **global** `videojs.Vhs` _and_ **player** `player.tech().xhr` scoped API functions to add these hooks, where player …
> feat(xhr): add request and response hook API

- README.md
- src/videojs-http-streaming.js
- src/xhr.js
- test/videojs-http-streaming.test.js
- test/xhr.test.js
The xhr wrapper calls `open` and `send` when a request object is instantiated, this is causing `onRequest` hooks to modify the xhr object too late, as they were already sent when the object was returned to the VHS xhr module. Additionally, setting xhr hooks in time for the initial manifest request when `preload` is set to `auto` or `metadata` is not possible with existing events or `ready` callbacks.
By calling all the `onRequest` hooks **before** we create the `request` object and passing the callback the `options` object instead, we can modify the request before `open` is called in the xhr wrapper. This `options` object allows for modifying the url/headers/methods, as well as setting a `beforeSend` callback, which gives the `onRequest` callback direct access to the `xhr` object via a …
> fix: onRequest hooks called too late

- package-lock.json
- package.json
Update m3u8 parser to add support for daterange and independent segment tags.
Update m3u8 parser in the package.json
> chore(package): update m3u8-parser v6.2.0

- docs/supported-features.md
- src/segment-loader.js
- test/loader-common.js
Adds support for [#EXT-X-INDEPENDENT-SEGMENTS](http://tools.ietf.org/html/draft-pantos-http-live-streaming#section-4.3.5.1) tags. This feature depends on [this PR](https://github.com/videojs/m3u8-parser/pull/165) in the m3u8 parser.
Allow VHS to respect `independentSegments` for m3u8 playlists. This will cause VHS to no longer look backward for the next `independent` segment if `independentSegments` is true in the main playlist _or_ the media playlist. If `independentSegments` is set in the main playlist, it will apply to every segment in every media playlist.
> feat: add support for independentSegments

- src/playback-watcher.js
- test/playback-watcher.test.js
Low latency streams can get into a bad state on startup and fail if the seek position is adjusted with the playback watcher, specifically by `fixesBadSeeks`. There are checks in that function that determine if a seek position is outside the seekable window. This seekable range is a calculated interval duration from the playlist, where the **end** of the seekable window is the `duration - HOLD-BACK`. When the player first calculates the seekable range from the manifest, the interval duration returned is not precise. Sometimes this non-precise duration will be greater than the precise duration determined after the playlist is loaded. Since the player uses the first, non-precise duration calculation to determine the start position of a live asset, if the precise duration is updated to a …
> fix(llhls): watcher causes playback failure

- package-lock.json
- package.json
- src/segment-loader.js
- src/sync-controller.js
- src/util/time.js
- test/playlist-loader.test.js
- test/segment-loader.test.js
- test/sync-controller.test.js
- test/util/time.test.js
Updates m3u8-parser version to 7.0, replaces `dateTimeObject` and `dateTimeString` with `programDateTime` and  fixes tests
> chore: update m3u8-parser version and fix tests

- src/segment-loader.js
- src/util/time.js
Adds `dateTimeObject` and `dateTimeString` back to segment metadata cues for backwards compatibility
> refactor: add dateTimeObject and dateTimeString to Cues for backwards compatibility

- src/segment-loader.js
- test/loader-common.js
After a LOT of debugging with playlist changes against a linear DASH stream, I discovered we're calling `resetLoader` when setting a new playlist (during a rendition switch), which sets `fetchAtBuffer_` to false then calls `resyncLoader`. This sets the `mediaIndex` to null, which eventually on the next `chooseNextRequest_` call (which as implied, chooses the next segment to request) forces us into the else logic. Because `fetchAtBuffer_` is false, we begin requesting segments from the `currentTime` rather than the end of the buffer. This causes the playback watcher to assume a segment download has stalled, because when we request segments at the `currentTime` we're either requesting cached segments or overwriting segments that were already buffered, which results in the buffer not …
> fix(live): only reset playlist loader for LLHLS

- src/util/text-tracks.js
When creating metadata cues, the last cue uses the videoDuration as the end time, in live playback this is `Infinity` and throws an error.
Add an `isFinite` check to the duration, if it's not finite we use 0 instead.
> fix(live): cue end time not finite

- package-lock.json
- package.json
- src/playlist-loader.js
- src/segment-loader.js
- src/sync-controller.js
- src/util/time.js
- test/playlist-loader.test.js
- test/segment-loader.test.js
- test/sync-controller.test.js
- test/util/time.test.js
This PR shouldn't be merged before 
Restores dateTimeObject and dateTimeString segment properties that were previously removed and refactored in these two PRs
- https://github.com/videojs/http-streaming/pull/1407
- https://github.com/videojs/http-streaming/pull/1409
> fix: restore dateTimeObject and dateTimeString usage

- src/playlist-controller.js
- test/playlist-controller.test.js
Removing the `abort` call from `setCurrentTime` makes seeking and certain playlist switching cases more resilient. This is because `setCurrentTime` was essentially calling abort on all the segment loaders twice. Once in the `setCurrentTime` function directly, then from `resetEverything` which eventually calls `resyncLoader` which also calls `abort` on the segment loader.
Remove the `abort` calls on all segment loaders and fix the tests.
> fix: remove segment loader abort in setCurrentTime

- src/playlist-controller.js
- src/videojs-http-streaming.js
The default playlist exclusion duration seemed arbitrarily long, especially for live playback. Lets reduce the default and the `earlyAbortWhenNeeded_` exclusion to seconds instead of minutes to allow for more live resiliency.
Reduce the default `playlistExclusionDuration` value from 5 minutes to 10 seconds. Also reduce the `ABORT_EARLY_EXCLUSION_SECONDS` from 2 minutes to 10 seconds.
> fix: reduce playlist exclusion defaults

- src/playlist-controller.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/playlist-controller.test.js
`fastQualityChange_` was causing unnecessary rebuffering and requesting cached segments. This was resulting in slow and very buggy playlist changes. This was because it was calling `resetEverything` on the mainSegmentLoader, then calling `setCurrentTime` which calls `resetEverything` again on ALL the segment loaders, which removes all content from the buffer and aborts all requests.
Edit: Had to add a property `replaceSegmentsUntil`, which represents the end of the buffer at the moment `fastQualityChange_` is called. This tells the segment loader to leave `fetchAtBuffer_` as false until we've successfully replaced all the buffered segments between `currentTime` and `bufferedEnd` at the moment `fastQualityChange_` is called.
Remove the `resetEverything` and `setCurrentTime` call from …
> fix: fastQualityChange refactor

- scripts/index.js
The VHS demo page representation selector was not allowing the user to select the first or `0` indexed representation in the list.
Remove the `!selectedIndex` check and change the expected index to `< 0 ` for "no element selected". See: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedIndex
> fix: demo page representation selector

- package-lock.json
- package.json
Update to the newest version of the mpd-parser to consume the work for content-steering
> chore: update mpd-parser to v1.2.2

- index.html
- scripts/index.js
Adds content steering information to the demo page.
Creating  a new tab in the demo page that displays the current state of the content steering controller and content steering manifest object within the controller.
> feat: content steering demo page tab

- index.html
- src/content-steering-controller.js
- src/dash-playlist-loader.js
- src/media-groups.js
- src/playlist-controller.js
- test/content-steering-controller.test.js
- test/dash-playlist-loader.test.js
- test/playlist-controller.test.js
The changes include the logic for switching pathways regarding content steering. All specifications for both DASH and HLS can be found in the resources below. The function of these changes are to ensure that we are communicating with the content steering server, handling the responses, switching playlists based on this data, and ensuring that we follow the requirements of the spec when deciding when/where to switch.
- Logic to determine which pathway/serviceLocation should be selected based on priority.
- Logic to switch media in cases where we want to switch playlists.
- Logic to exclude playlists when necessary according to the spec.
- Logic to set timers to retry certain content steering requests.
- Tests to cover specification
DASH: …
> feat: content steering switching

- src/playlist.js
- test/playlist.test.js
We have default `liveEdgePadding` as 3 * targetDuration. 
Assume we have a stream with a maximum of three segments. 
Each segment's actual duration is less than a `targetDuration`. 
In this scenario, we may have a `seekable.end` less than a `seekable.start`. 
This may lead to unexpected behavior.
Clamp `seekable.end` to make sure that it is more or equal to `seekable start`.
> Clamp seekable end

- src/media-segment-request.js
Fixes an issue where caption data wasn't being passed out to the transmuxer callback for parsing.
Use the correctly scoped data object.
> fix: fmp4 captions regression

- src/playlist-controller.js
This fixes a regression introduced in 4590bdd05aa2dd59bb2b60ce86daf453a093fba0
If the quality is changed during initialization, this function is called. Since `buffered.length` is zero and `buffered` is a [TimeRanges](https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges), `length` (an `unsigned long`) wraps around and becomes `4294967295`
```
PsVideo.ts:462 DOMException: Failed to execute 'end' on 'TimeRanges': The index provided (4294967295) is greater than the maximum bound (0).
at PlaylistController.resetMainLoaderReplaceSegments (http://localhost:8035/apps/memories/js/memories-vendors-node_modules_plyr_dist_plyr_css-node_modules_video_js_dist_video-js_min_css-node_modu-82e78d.js?v=7e8851a5e7ef114c9398:65070:34)
at PlaylistController.fastQualityChange_ …
```
> fix regression: prevent wrapping in resetMainLoaderReplaceSegments

- src/content-steering-controller.js
- src/dash-playlist-loader.js
- src/playlist-controller.js
- test/content-steering-controller.test.js
- test/dash-playlist-loader.test.js
- test/playlist-controller.test.js
This PR addresses a few content steering bugs and ads some additional testing around live DASH.
Refactoring the content steering initialization to attach listeners separately, change some `queryBeforeStart` behavior and an issue with the initial `ttl` value.
> fix: content steering bug fixes and tests

- src/content-steering-controller.js
- src/manifest.js
- src/playlist-controller.js
- src/playlist-loader.js
- test/playlist-controller.test.js
- test/playlist-loader.test.js
Implementation for HLS Pathway cloning for content steering. See the spec here: https://datatracker.ietf.org/doc/draft-pantos-hls-rfc8216bis/
Whenever we get a response from the content server with a `PATHWAY-CLONES` array, we need to add, update, or delete playlists and media based on the data we receive. A pathway clone object tells us information about a new pathway that should be created/updated based off of another pathway.
- Store the pathway cloning data retrieved from the server reponse in the content steering controlelr.
- Add a new pathway with playlist and media data when the pathway clone did not exist previously.
- Update playlist and media data from a previously existing pathway clone when we get new data from the pathway clone object.
- Delete playlist and media data from a …
> feat: Content Steering HLS Pathway Cloning

- src/util/text-tracks.js
We shouldn't set endTime to 0, instead we should set it to the startTime if we don't have a duration.
replace 0 with startTime
> fix: use startTime instead of 0 for finiteDuration

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
Public function for updating VHS options. This gives the user a way top update VHS config after initialization of the player.
* Create `setOptions` function
> feat: Public function for updating VHS options

- src/segment-loader.js
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.
Please list the specific changes involved in this pull request.
> fix: replaceSegmentsUntil flag resetting too early

- src/playlist-controller.js
- src/segment-loader.js
- src/sync-controller.js
- test/playlist-controller.test.js
- test/segment-loader.test.js
- test/videojs-http-streaming.test.js
- implement a new sync strategy based on the media sequence
- implement exact match for sync controller
- fix fast quality switch race condition
- implement force timestamp offset after resync loader
> Sync controller media sequence strategy

- package-lock.json
- package.json
Update mpd-parser to v1.3.0
update the package.json and package-lock.json to 1.3.0 for the mpd-parser
> chore: update mpd-parser to v1.3.0

- package-lock.json
- package.json
- src/dash-playlist-loader.js
- src/playlist-controller.js
- src/playlist-loader.js
- src/util/string.js
- src/videojs-http-streaming.js
- test/dash-playlist-loader.test.js
- test/playlist-controller.test.js
- test/playlist-loader.test.js
- test/videojs-http-streaming.test.js
Only enable playlists with a 'usable' keystatus when playing DASH with DRM.
Reference the playlist keyId after getting a `keystatuschange` event from contrib-eme and only enable encrypted playlists that we have a matching usable keyId for.
Note: This PR includes changes from #1461
> feat: enable playlists with 'usable' keystatus

- src/dash-playlist-loader.js
- src/playlist-controller.js
- src/playlist-loader.js
- test/dash-playlist-loader.test.js
- test/playlist-loader.test.js
- test/videojs-http-streaming.test.js
Manifests with uppercase keyIds were not matching with keyIds coming from the MediaKeyStatusMap. Also occasionally we would buffer encrypted content that we may not have a key for, we need to call fastQualityChange to clear the buffer before switching playlists.
Add `toLowerCase` to the keyId from the manifest when passing the keyIdSet for playlist filtering and call `fastQualityChange` instead of `switchMedia` then fix tests.
> fix: toLowerCase keyIds from manifest and use fastQualityChange

- src/playlist.js
- test/loader-common.js
- test/playlist.test.js
- test/segment-loader.test.js
- test/vtt-segment-loader.test.js
Assume we have the following playlist:
``` shell
#EXTINF:6.000,
segment-1.ts
#EXTINF:6.000,
segment-2.ts
#EXTINF:6.000,
segment-3.ts
#EXTINF:6.000,
segment-4.ts
#EXTINF:6.000,
segment-5.ts
#EXTINF:6.000,
segment-6.ts
...
```
Assume we switch rendition based on bandwidth update. 
We are selecting the next segment to load based on the buffered.end (assume current buffered is [0 - 12]).
Currently, we select `segment-2.ts`, but it is already buffered.
or assume we switch rendition based on a fast quality switch.
We are selecting the next segment to load based on the current time (current time is 12).
Currently, we select `segment-2.ts` but it is already played.
in both cases, we should select the next segment (`segment-3.ts`)
Select the next segment when we are at the exact segment.end …
> fix: select next if we are at the of the current segment

- src/playlist-controller.js
- test/playlist-controller.test.js
After doing some further testing with HLS and playlist exclusion by keyId, it became apparent some more fixes were needed to properly request and filter all possible variants.
I also added a fallback mechanism and additional logging. I was testing another asset with no matching keys and it seemed necessary to at least _TRY_ and play the non-HD playlists if we have previously excluded them due to non-usable or non-matching keyIds.
Listening to `loadedplaylist` and calling `excludeNonUsablePlaylistsByKeyId_` and `fastQualityChange` when a new playlist is loaded. This allows the `playlist-controller` to check the keyId in the loaded or refreshed playlist for an HLS variant, or a refreshed DASH manifest.
Also, add a conditional after the playlist exclusion loop that checks if we excluded all …
> fix: keyId filtering loadedplaylist listener and improvements

- src/playlist.js
we should account for the difference between the duration info in the manifest and the actual duration of the segment when selecting next segment after quality change.
Assume we have the following playlist:
```shell
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:10
#EXTINF:10.000,
segment-1.ts
#EXTINF:10.000,
segment-2.ts
#EXTINF:10.000,
segment-3.ts
#EXTINF:10.000,
segment-4.ts
#EXT-X-ENDLIST
```
Assume we already appended two segments, so `bufferend.end` should be `20`, but we don't have an exact duration match between the playlist and the actual segment duration, so we receive it as `19.99999..`. 
Currently, we select segment-2.ts instead of segment-3.ts because we do not account for this timestamp fluctuation.
Check whether we hit …
> fix: account for difference between duration info in the playlist and the actual duration

- src/source-updater.js
This change will fix an error on change to the provided codec which is not supported.
Just warn about it and do not freeze the video.
> fix: check if change to the provided type is supported

- src/content-steering-controller.js
- src/dash-playlist-loader.js
- src/media-segment-request.js
- src/playlist-loader.js
- src/xhr.js
Adding request types for each request
> feat: add request types

- src/playlist.js
- src/segment-loader.js
- test/loader-common.js
- test/playback.test.js
- test/playlist.test.js
We may encounter duplicate segment loading during bandwidth updates.
Since we are re-calculating timestampOffset during each quality switch it results in presenting of duplicate segments.
Consider the following situation:
This log is placed in the `chooseNextRequest_`. 
As you can see:
- The player selected MediaSequence 28 from playlist A. 
- Then, the player switched quality to playlist B because of the bandwidth update.
- Then, the player selected MediaSequence 28 despite the fact that it was already buffered from the previous playlist.
- This happens because of the slight difference between the buffered.end and the sum of durations from the playlist.
Make an assumption that some segment or segment's part is already buffered if the difference between segment.end and buffered.end is …
> Fix repeated segments issue during bandwidth update

- src/source-updater.js
Call changeType only when the codec base has changed.
Parse the codec base from the new codec and the existing codec for the given track and compare that to determine if we need to call changeType on the source buffer.
> fix: changeType on full codec change only

- src/playlist.js
- src/segment-loader.js
- test/loader-common.js
- test/playback.test.js
- test/playlist.test.js
Reverts videojs/http-streaming#1477
> Revert "Fix repeated segments issue during bandwidth update"

- scripts/index.js
Removes an error on the demo page with native playback from an unguarded call to property on `player.tech_.vhs`
Using `&&` since this page should be usable on old Chrome.
> chore(demo): Remove error on iOS on demo page

- README.md
- src/playlist-selectors.js
- src/videojs-http-streaming.js
- test/configuration.test.js
- test/playlist-selectors.test.js
An optional `customPixelRatio` parameter. This enables the ABR algorithm to act as if the player dimensions were multiplied by a number greater than 0. The benefits of this are to manipulate the player to select higher renditions if better quality video is required, or lower renditions if it is desired to save on bandwidth.
Example:
if you have a player where the dimension is `540p`, with a custom pixel ratio of `2`, a rendition of `1080p` or a lower rendition closest to this value  will be chosen.
- Expect an optional `customPixelRatio` option.
- Multiply the pixelRatio used in our ABR by this value.
- Tests regarding rendition selection
- Documentation
- ~[ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))~
> feat: Custom Pixel Ratio

- package-lock.json
- package.json
update mux.js to v7.0.3
This includes a fix for some unexpected 608 caption behavior.
> chore: update mux.js to v7.0.3

- src/segment-loader.js
timestampOffset was being reset on LL-HLS quality changes. We only want to force timestampOffset changes on rendition switches for `.ts` segments due to the timestamp rollover problem in those containers.
Check if the current media is fmp4, if it is don't force the timestampOffset reset after a resync of the segment loader.
> fix: llHLS does not need forcedTimestampOffset

- scripts/index.js
- src/rendition-mixin.js
Our rendition mixin `enableFunction` is used to select a rendition/variant for playback. This function uses the playlist controller `fastQualityChange_` to do this switch, however we were not passing the playlist during this call, resulting in inconsistent quality switches due to the next playlist coming from a `selectPlaylist()` call instead of user selection.
Pass playlist as a parameter during the `fastQualityChange_` /`changePlaylistFn` call
> fix: enableFunction not passing playlist to fastQualityChange

- docs/multiple-alternative-audio-tracks.md
Looking through docs I found a duplicated step
Remove duplicated step in multiple-alternative-audio-tracks doc
> docs: removing duplicated step

- src/sync-controller.js
- src/util/media-sequence-sync.js
`audio` and `vtt` segment loaders are opt-in features and can be enabled after the `main` start. (eg: via UI)
We should align the media sequence start time with the `main` for them.
Use `parent` for `vtt` and `audio` media sequence storages.
`parent` should be `main`.
> fix: use paren media sequence sync for audio and vtt, since they are opt-in features and can be enabled after main init.

- package-lock.json
- package.json
- src/content-steering-controller.js
- src/dash-playlist-loader.js
- src/error-codes.js
- src/media-segment-request.js
- src/playback-watcher.js
- src/playlist-controller.js
- src/playlist-loader.js
- src/rendition-mixin.js
- src/segment-loader.js
- src/segment-transmuxer.js
- src/source-updater.js
- src/timeline-change-controller.js
- src/util/container-request.js
- src/videojs-http-streaming.js
- src/vtt-segment-loader.js
- src/xhr.js
- test/dash-playlist-loader.test.js
- test/media-segment-request.test.js
- test/playback.test.js
- test/playlist-controller.test.js
- test/segment-loader.test.js
- test/segment-transmuxer.test.js
- test/videojs-http-streaming.test.js
Adding some additional events and errors with relevant payloads to VHS to enable users to centralize streaming events and utilize the information passed with each error and event payload to inform their video playback code.
Add events and payloads for all phases of  playback from manifest/playlist request - load - parse. Segment load - transmux/parse/decrypt - append. Errors and relevant payloads for common network, segment and playlist/manifest conditions.
> feat: streaming events and errors

- package-lock.json
- package.json
update the peer dependency `videojs-contrib-eme` to v5.3.1
update `videojs-contrib-eme` to v5.3.1
> chore: update contrib-eme to v5.3.1

- src/media-segment-request.js
- test/media-segment-request.test.js
When handling a encrypted init segment `-init` was being added to the `requestId` erroneously. 
- Remove the `-init` addition, as it is added to the id below when the request is made without changing the actual requestId itself.
- Add a test to ensure requestId is unchanged when decrypting an init segment.
> fix: requestId init tag

- src/source-updater.js
fix videoTimestampOffset comparison
add `_` to `this.videoTimestampOffset` so we compare the value instead of the function. 😁
> fix: videoTimestampOffset in sourceUpdater

- .github/workflows/ci.yml
Updates to v4 of codecov which is more robust with uploads from PRs from forks.
> chore: Update codecov action

- index.html
- scripts/index.js
Adds the option to download or copy logs to the demo page. Concenates the page URL, versions, user agent and `player.log.history()`.
> chore: Add log export to the demo page

- src/playback-watcher.js
- src/playlist-controller.js
- test/playlist-controller.test.js
Currently, our fastQualitySwitch triggers a full video/main buffer clear twice. This is because we clear the buffer first with a `resetEverything` call on the mainSegmentLoader, then once that removal is complete we call `setCurrentTime` which calls `resetEverything` on all active segment loaders, clearing all the other buffers as well. This is causing some instability, specifically when a quality change occurs at or near a discontinuity.
Instead of calling `setCurrentTime` after a fastQualitySwitch, lets just call `load` on the mainSegmentLoader.
Note: There were 2 browser bugs that seemed to require a `setCurrentTime` call according to the comments, but after checking both URLs, those bugs seem to no longer be relevant, so we should be safe removing this part and only calling load.
> fix: fastQualitySwitch stability

- src/playlist-controller.js
- src/segment-loader.js
- test/playlist-controller.test.js
- test/segment-loader.test.js
Currently there is an edge case in DASH where certain points of audio segments and video segments do not always exist on the same timeline.
Example: We seek to `100` seconds into the video. There is an audio segment that is from 98-100.25 seconds, and the video segment is from 100-109.95. The audio segment is on a timeline from 90-99.99, and the video segment is on a timeline from 110-119.99. We fall into a loop in this scenario because VHS catches that we have bad timelines, but we do not do anything to fix it in this scenario.
This change allows us to check for this specific scenario. When we attempt to load an audio segment that is on a prior timeline to the video segment, we will now force the player forward to just past the faulty audio segment. This ensures that the audio and video …
> fix: audio segment on incorrect timeline

- package-lock.json
- package.json
m3u8-parsrer to 7.3.0
vhs-utils to 4.1.1
aes-decrypter to 4.0.2
> chore: update m3u8-parser, vhs-utils and aes-decrypter

- src/vtt-segment-loader.js
Allow `handleRollover` to be called on vtt segments when the `MPEGTS` value from the `X-TIMESTAMP-MAP` tag is 0
Remove the `MPEGTS === 0` check and associated ternary.
> fix: allow vtt rollover with MPEGTS of 0

- src/playlist-controller.js
- src/segment-loader.js
- test/segment-loader.test.js
Related to https://github.com/videojs/http-streaming/pull/1530
This fixes an issue that was previously thought to just happen in DASH above. Now, in HLS, if the audio segment in on a previous timeline to the video segment, we will push playback to where they are both on the same timeline.
- Removes the DASH safeguards in the audio segment behind timeline logic so this covers HLS as well.
> fix: audio segment on incorrect timeline HLS

- package.json
- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
**Note:** This depends on https://github.com/videojs/video.js/pull/8886. Before we merge this, we will need a new Video.js release and then have to bump the peer dependency version in this package.
This PR adds Airplay support when overriding native HLS in Safari and/or iOS by using two `source` elements, one for the MediaSource URL object and one for the Airplay-compatible manifest URL.
From the Webkit guide on [Airplay and MSE](https://webkit.org/blog/15036/how-to-use-media-source-extensions-with-airplay): 
> When Safari detects that an alternative source is available in addition to the MediaSource URL object, it will display the familiar AirPlay icon to the video player control. Should the user select AirPlay, it will switch over from MSE to the AirPlay-compatible URL.
If we are …
> feat: Add Airplay support when overriding native HLS in Safari/iOS

- src/playlist-controller.js
- test/playlist-controller.test.js
This PR adds onto the experimental support for `ManagedMediaSource`. When the user agent determines that a ManagedMediaSource has enough data buffered to ensure uninterrupted playback, or does not have enough to ensure it, it will fire a `endstreaming` or `startstreaming` event, indicating that the player should stop loading new segments or start loading new segments, respectively.
Add 2 new event handlers for `startstreaming` and `endstreaming`. The former will call `playlistController.load()`, which was a preexisting method that calls `load()` on all active segment loaders. The latter calls `playlistController.pause()`, which is a new method that calls `pause()` on all active segment loaders.
https://www.w3.org/TR/media-source-2/#dom-managedmediasource-streaming …
> feat: Add support for ManagedMediaSource 'startstreaming' and 'endstream' event handling

- src/dash-playlist-loader.js
- src/playlist-controller.js
- src/rendition-mixin.js
- src/segment-loader.js
- src/util/fn.js
- test/playlist-controller.test.js
- test/rendition-mixin.test.js
- test/segment-loader.test.js
- test/videojs-http-streaming.test.js
- Clear timeout for media request in dash playlist loader. This fixes the incorrect clearing logic for the media request timeout in the dash playlist loader.
- Add light debounce for fast quality change. This fixes duplicate calls during rapid quality switching.
For example, when we select quality from the quality list with multiple bandwidth profiles for the same vertical resolution, it will call for fast quality changes for multiple playlists one by one.
- Add `isPaused` for the dash playlist loader. This fixes duplicate load calls when `mediachange` is fired. See this PR for more info https://github.com/videojs/http-streaming/pull/1339)
- Call fast quality change only if a playlist is selected. This fixes duplicate calls when selecting quality from the quality list.
- Ignore duplicate …
> Multi period dash VOD fixes

- README.md
Heya, fixed a link in the Readme. Had to open this a couple of times in the last two days and it bothered me...
btw: Thanks for the nice Documentation with all the links! :-)
fixed a link in the Readme
- [/] Feature implemented / Bug fixed
> Updated link in readme leading to Decode Timestamp doc at w3.org

- src/error-codes.js
The erroType property in request.timedout is incorrectly named.
While reviewing error-handling behavior, I noticed an inconsistency in the property name. 🔍 Based on the surrounding code context, it should be errorType.
This fix ensures consistency with other error return formats😀
correct errorMetadata property name from `erroType` to `errorType`
> fix: correct errorMetadata property name from 'erroType' to 'errorType'
