videojs/http-streaming

- README.md
- package-lock.json
- package.json
- test/karma.conf.js
Runs tests on http://browserstack.com when available.
> test: use browserstack for running tests

- package-lock.json
- package.json
Update the mpd-parser to pick up new features
> update mpd-parser to support more segment list types

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
closes https://github.com/videojs/http-streaming/issues/18
> ignore: update jsbin example

- README.md
> Remove IE10 section from the README

- src/master-playlist-controller.js
> add debug logging statement for seekable updates

- package.json
- src/media-groups.js
- src/source-updater.js
- src/util/noop.js
- src/videojs-http-streaming.js
- test/karma.conf.js
- test/media-groups.test.js
- test/playback-watcher.test.js
> ignore: Code coverage

- package-lock.json
- package.json
Update the mpd-parser to pick up more features.
https://github.com/videojs/mpd-parser/commit/8e59b382b716d7cd85229a4ea277dfad4747cb8b
> feat: Adding support for segments in Period and Representation

- package-lock.json
- package.json
Makes browserify-versionify a dependency so downstream projects will build correctly
> fix: make browserify-versionify a dependency

- src/dash-playlist-loader.js
- src/playlist-loader.js
- src/videojs-http-streaming.js
Update the parser imports to use the exposed APIs.
> fix: correct parser usage

- index.html
This makes it so that the page functions whether via `npm start` or some
other local web server.
> chore: make index.html urls relative

- package-lock.json
- package.json
- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
Added support for detecting in-manifest DRM data.
> feat: support in-manifest DRM data

- package-lock.json
- package.json
- src/decrypter-worker.js
- src/videojs-http-streaming.js
- test/karma.conf.js
Updating the `aes-decrypter` to use the rolled up version of the project.
Also bumping up the Qunit test timeout because the playback test sometimes takes longer than 5s
> chore: update the aes-decrypter

- .github/move.yml
- .github/stale.yml
This adds some bots to handle issues
> ignore: issue bots

- .github/config.yml
Copied from https://github.com/videojs/video.js/pull/5313
> Add welcome templates (from video.js)

- test/playback.test.js
Added skipped fmp4 test against playlist with both ts and fmp4 segments which will be enabled once we've added the feature.
> Added skipped fmp4 test

- .github/ISSUE_TEMPLATE.md
Update the issue template to include a link to the troubleshooting doc and a note about deleting the template
> docs: update issue template to link to the troubleshooting guide

- docs/troubleshooting.md
> Troubleshooting thumbcoil link

- src/util/time.js
- src/videojs-http-streaming.js
- test/util/time.test.js
- test/videojs-http-streaming.test.js
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.
Please list the specific changes involved in this pull request.
> feat: add convertToStreamTime method

- COLLABORATOR_GUIDE.md
> Add COLLABORATOR_GUIDE.md with section on releases

- package-lock.json
- package.json
> ignore: update npm-run-all to 4.1.5

- docs/troubleshooting.md
> ignore: add a troubleshooting entry around network requests while paused

- src/master-playlist-controller.js
- src/playlist-loader.js
- test/videojs-http-streaming.test.js
This reverts commit 6e6c8c212d5da1a5b5d297ff1e513f86ef46bb15.
> revert: "fix: clear the blacklist for other playlists if final rendition errors (#396)"

- src/vtt-segment-loader.js
> fix: remove both vttjs listeners to prevent leaking one of them

- README.md
Just editing the README to document a couple of our known issues, and add workarounds where appropriate.
Let me know if there are others I forgot about.
> docs: add more known issues and workarounds

- package-lock.json
- package.json
Mostly Muxer changes to get this working, ~~but we did miss a function in trasmuxer-worker.js...~~ EDIT nevermind
Depends on https://github.com/videojs/mux.js/pull/277
> fix: Alternative audio with handlePartialData

- src/segment-loader.js
- test/playback.test.js
- test/videojs-http-streaming.test.js
- test/vtt-segment-loader.test.js
Make the playback tests faster using `playbackRate`
> test: faster playback tests

- src/segment-loader.js
- src/util/text-tracks.js
- src/vtt-segment-loader.js
- test/segment-loader.test.js
Only remove cues in a specific time range.
> fix: remove captions within a range

- src/dash-playlist-loader.js
Fix bug when sidx was activated even for playlists without sidx
https://github.com/videojs/http-streaming/issues/457 + https://github.com/videojs/http-streaming/issues/557
> fix: Sidx is activated for playlists which have no sidx #457

- scripts/create-test-segments.js
- scripts/karma.conf.js
- src/source-updater.js
- test/loader-common.js
- test/master-playlist-controller.test.js
- test/playback-watcher.test.js
- test/playback.test.js
- test/sanity.test.js
- test/segment-loader.test.js
- test/source-updater.test.js
- test/videojs-http-streaming.test.js
- test/vtt-segment-loader.test.js
Currently tests don't run on ie11 or edge, this pull requests makes that happen again.
> WIP test: run tests on edge and ie11

- scripts/index-demo-page.js
- scripts/netlify.js
Since `type` is text and not url it was being treated like a text box and not loaded correctly from the url. This fixes that.
> fix: Load type from url correctly

- src/ranges.js
- test/ranges.test.js
> fix: Issues with video stutter at the start of playback.

- src/mse/transmuxer-worker.js
- src/segment-loader.js
> perf: save 15430 gzipped bytes with better mux.js import

- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
Similar to Advanced plugins in `video.js`
> feat: expose version on `player.vhs.version()` and `HlsHandler.version`

- package-lock.json
- package.json
- src/sync-controller.js
- test/segment-loader.test.js
- test/sync-controller.test.js
#660 
(I previously merged instead of squash + merge, so this is a redo)
> fix: improve timestampOffset calculation for fmp4s

- package-lock.json
- package.json
- src/master-playlist-controller.js
- src/playlist-selectors.js
- src/util/codecs.js
- src/videojs-http-streaming.js
- test/util/codecs.test.js
- test/videojs-http-streaming.test.js
> Update vhs-utils to v1.2.0 and import functions added to vhs-utils

- index.html
- scripts/netlify.js
- src/rendition-mixin.js
- src/videojs-http-streaming.js
- test/videojs-http-streaming.test.js
- utils/stats/index.html
> fix: race condition preventing qualityLevels from populating (#707 from 1.x)

- src/master-playlist-controller.js
- src/playlist.js
- test/master-playlist-controller.test.js
- test/playlist.test.js
This is a port of #698 against master.
> feat: support suggestedPresentationDelay in DASH manifests

- src/dash-playlist-loader.js
- src/master-playlist-controller.js
- src/mse/html-media-source.js
- src/mse/virtual-source-buffer.js
- src/playlist-loader.js
- src/segment-loader.js
- src/sync-controller.js
> fix: add dispose functions and fix memory leaks #643 for 1.x

- utils/stats/index.html
- utils/stats/stats.css
https://github.com/videojs/http-streaming/pull/695 for master
> chore(stats): add liveui option and various fixes (#695)

- package-lock.json
- package.json
Fixes seeking backwards in some hls live streams.
> fix: Seeking back in a Live stream, via mux.js update

- README.md
See https://github.com/videojs/http-streaming/issues/761
> ignore: update README with example of listening to usage events

- src/master-playlist-controller.js
- src/mse/virtual-source-buffer.js
I missed terminating workers on dispose for 1.x.
> fix: dispose workers on dispose

- package-lock.json
- package.json
> fix: update mpd-parser to 0.10.1 to fix some SIDX DASH sources

- package-lock.json
- package.json
Update mux.js in 1.x
Fixes #798
> chore(package): update muxjs to 5.5.3

- test/master-playlist-controller.test.js
> test: append one after another

- index.html
- scripts/index-demo-page.js
1. I found myself hitting enter in the url box or type box a lot. 
2. I often look for the exact type of dash/hls to copy paste.
3. ie 11 only half works as it does not support `URLSearchParams` I added a polyfill of sorts.
> chore(demo): demo type examples, ie 11 support, hit enter in type/url

- scripts/index-demo-page.js
Now that we load our sources async using json the `select` for sources isn't setting selectedIndex correctly. This is a fix for that.
> chore: demo page select matching url should be selected

- package-lock.json
- package.json
- scripts/index-demo-page.js
1. Update `mux.js` to the most recent version. 
1. `selectedIndex` can be `0` so we need to check if `selectIndex` is a number before setting it to `-1` or else if the first dropdown source is selected, ie 0, we will set the dropdown to -1.
> chore: update muxjs and allow 0 index for demo selectedIndex

- package-lock.json
- package.json
See https://github.com/videojs/mux.js/pull/334 for more information.
> chore(package): update muxjs to fix alternative audio switching

- package-lock.json
- package.json
We have fixed various issues in mux and need to get those changes into 1.x
> chore(package): update muxjs to fix various issues

- scripts/index-demo-page.js
- scripts/sources.json
For some of the sources in the dropdown we can't guess the mimetype, but we already provide it. We should use it in those cases. Also we need to reset `selectIndex` every time the source is changed so that it is always accurate.
> chore: better selectedIndex and use mimetype

- src/segment-loader.js
- test/segment-loader.test.js
> fix: consider whether audio is enabled for main segment loader buffered ranges

- README.md
- src/playlist-selectors.js
- src/videojs-http-streaming.js
- test/configuration.test.js
> fix: put devicePixelRatio behind useDevicePixelRatio option

- src/videojs-http-streaming.js
> refactor(BREAKING): rm aes-decrypter objects from Hls saving 1415gz bytes

- src/master-playlist-controller.js
Fixes the `this.el_` failure that we have been seeing with firefox sometimes. Also a memory leak.
> fix: cleanup mediasource listeners

- scripts/index-demo-page.js
Tired of typing: `player.tech_.vhs.masterPlaylistController_`
> chore: Add vhs and mpc (vhs.masterPlaylistController_) to window in index.html

- scripts/sources.json
The widevine server doesn't really work for playready ;)
> chore: use playready license server

- src/playlist-selectors.js
I was using some logging for debugging the selector, but I think that it would be more broadly useful so I added it.
> chore: playlist selector logging

- package-lock.json
- package.json
> chore: update m3u8-parser to v4.4.3

- src/segment-loader.js
- test/segment-loader.test.js
OK so this bug was a doozy to try to understand. What happens with one of our demuxed videos is:
1. We fetch and append segment 0 for video and audio segment loader
2. We fetch and append segment 1 for video and audio segment loader
3. Rendition switch happens for video
4. We fetch and append segment 2 for audio
5. We fetch and append segment 0 again for video because:
* `buffered_()` returns an empty buffered `TimeRange` as we don't have `startingMedia_` yet.
* This causes us to grab content at `0` again as current time is within that range and buffered has no length. (see `SegmentLoader#checkBuffer_`)
6. We video underflow and the content freezes as the invalid append does not fail, but also never `updateend`
1. The current one: store what we call `startingMedia` in a variable that is …
> fix: report the correct buffered regardless of playlist change

- scripts/sources.json
Subs are broken or just blank for this video, add a TODO to investigate in the source name so that we don't worry when subs are broken.
> chore: mark angel one dash subs as broken

- src/videojs-http-streaming.js
- test/master-playlist-controller.test.js
- test/videojs-http-streaming.test.js
> fix: check tech error before pause

- .github/workflows/ci.yml
Testing out https://github.com/marketplace/actions/skip-duplicate-actions
> chore: skip duplicate ci workflows

- package-lock.json
- package.json
- scripts/rollup.config.js
Removes the code for replace and updates  generator dependencies.
> chore: remove replace and update packages

- src/manifest.js
- src/playlist-loader.js
We have logs in m3u8-parser that we have yet to use, with the onset of ll-hls there will be even more logs. We should use these logs in our debug logger.
> feat: expose m3u8-parser logging in debug log

- scripts/sources.json
Add sources to help us test Program Date Time
> chore: add pdt test sources

- package-lock.json
- package.json
Switching to rollup-plugin-worker-factory broke the minified bundle :( this should fix it.
> fix: unbreak the minified build by updating rollup-pluginworker-factory

- package-lock.json
- package.json
See changelogs in those projects for relevant fixes/changes.
> fix: update to mux.js@5.9.2 and mpd-parser@0.15.4

- src/util/segment.js
Fixes the issue seen in https://github.com/videojs/mux.js/pull/370 but further up stream.
> fix: prevent changing undefined baseStartTime to NaN

- src/segment-loader.js
- src/source-updater.js
- test/segment-loader.test.js
Call remove on QUOTA_EXCEEDED, fix coverage unit tests, catch source updater remove errors
> fix: catch remove errors, remove all data on QUOTA_EXCEEDED

- package-lock.json
- package.json
See the [vhs-utils changelog](https://github.com/videojs/vhs-utils/blob/main/CHANGELOG.md#301-2021-04-29) for changes
> chore: update vhs utils to 3.0.1

- package-lock.json
- package.json
Updates m3u8-parser and videojs-contrib-eme
> chore: m3u8-parser/eme updates

- package-lock.json
- package.json
> fix: ts segments that don't define all streams in the first pmt

- utils/stats/index.html
- Flash isn't a thing anymore
- Use the CloudFront URL by default
> chore: update utils/stats

- .github/workflows/ci.yml
Testing to see if we can skip playback tests for forks like this.
> chore: skip playback tests in forks

- .github/workflows/ci.yml
Testing with the new cache option.
> chore: use the new npm cache option when setting up node

- package-lock.json
- package.json
See https://github.com/videojs/mux.js/pull/393
> fix: encode correct video width/height in transmuxed mp4

- src/playback-watcher.js
- src/playlist-loader.js
- src/ranges.js
- test/playback-watcher.test.js
- test/ranges.test.js
playback watcher should seek us out of a gap that was seeked into.
> fix: playback watcher should fix seeking into a gap.

- test/loader-common.js
Moving this out of #1199 so that we can get it done quicker
> test: fix ie 11 race condition in tests

- package-lock.json
- package.json
See https://github.com/videojs/mux.js/blob/main/CHANGELOG.md#5141-2021-10-14
> fix(package): update mux.js to 5.14.1

- package-lock.json
- package.json
- src/bin-utils.js
Depends on videojs/vhs-utils#33
Fixes #1134
> fix: ArrayBuffer.isView may not be available everywhere

- README.md
- src/master-playlist-controller.js
- src/rendition-mixin.js
- src/videojs-http-streaming.js
- test/master-playlist-controller.test.js
- test/rendition-mixin.test.js
- test/segment-loader.test.js
Removes deprecated `smoothQualityChange` option
> Remove deprecated smooth quality change

- src/playback-watcher.js
- test/playback-watcher.test.js
Skips detected gaps immediately instead of waiting the duration of the gap before skipping
> feat: Skip gaps immediately

- scripts/index.js
- src/manifest.js
- src/playlist-controller.js
- src/playlist-loader.js
- src/playlist-selectors.js
- src/playlist.js
- src/segment-loader.js
- src/videojs-http-streaming.js
- test/playlist-controller.test.js
- test/playlist-loader.test.js
- test/playlist-selectors.test.js
- test/playlist.test.js
Removed some experimental options and make them default.
> feat: remove experimental options

- package-lock.json
- package.json
Resolves xmlparser vulnerability in `next`
> chore: update mpd-parser to 1.0.1

- package-lock.json
- package.json
Resolves xmlparser vulnerability in `main`
> chore: update mpd-parser to 0.22.1

- CHANGELOG.md
Changelog is missing a bug fix in the 3.0.1 release.
Add the bug fix to the changelog.
> chore(changelog): add missing bug fix

- package-lock.json
- package.json
mpd-parser version bump for a bugfix.
Update the package.json mpd-parser version to v1.1.1
> chore: update mpd-parser to 1.1.1

- package-lock.json
- package.json
Updating the mpd-parser dependency to v1.2.1
> chore: update mpd-parser to v1.2.1

- package-lock.json
- package.json
> chore: update mux.js to v7.0.1

- src/source-updater.js
cherry-pick of the https://github.com/videojs/http-streaming/pull/1463 into main
> fix: Check if change to the provided type is supported (#1463)

- package-lock.json
- package.json
Version bump for mpd-parser
Package update
> chore: update mpd-parser to v1.3.1
